import 'dart:math' as math;

import '../geometry.dart';
import '../operation.dart';
import '../timing_gate.dart';
import 'vbo_limits.dart';
import 'vbo_text.dart';

/// The one RaceChrono export verified to write arc-minutes and centre-direction
/// timing gates (VBOOverlay docs/testing.md).
const String raceChronoValidatedExporter = 'Generated by RaceChrono Pro v10.2.4';

/// What the file says about its coordinate unit. Coordinates are never
/// guessed from the numbers.
final class CoordinateEvidence {
  CoordinateUnit? unit;
  String source = '';
  String error = '';
  bool raceChrono = false;
  bool centreDirection = false;
}

/// The axis a column holds, by its exact (case-insensitive) name.
CoordinateAxis? coordinateAxisForName(String name) {
  final lower = name.toLowerCase();
  if (lower == 'lat' || lower == 'latitude') return CoordinateAxis.latitude;
  if (lower == 'lon' || lower == 'long' || lower == 'longitude') {
    return CoordinateAxis.longitude;
  }
  return null;
}

final RegExp _unitSeparator = RegExp('[:=]');

CoordinateEvidence resolveCoordinateEvidence(
  Map<String, List<String>> sections,
  CancellationCheck? cancelled,
) {
  final evidence = CoordinateEvidence();
  var exporter = '';
  var conflictingExporters = false;
  var visited = 0;
  for (final comment in sections['comments'] ?? const <String>[]) {
    if ((visited++ & 0xff) == 0) throwIfCancelled(cancelled);
    if (!startsWithIgnoreCase(comment, 'Generated by ')) continue;
    if (exporter.isNotEmpty && !equalsIgnoreCase(exporter, comment)) {
      conflictingExporters = true;
    }
    exporter = comment;
    evidence.raceChrono |= startsWithIgnoreCase(comment, 'Generated by RaceChrono');
  }
  evidence.centreDirection =
      !conflictingExporters && equalsIgnoreCase(exporter, raceChronoValidatedExporter);
  if (evidence.centreDirection) {
    // Samples and gate records both use signed total arc-minutes.
    evidence.unit = CoordinateUnit.arcMinutes;
    evidence.source = 'racechrono-pro-10.2.4';
  }
  if (conflictingExporters) evidence.error = 'conflicting exporter declarations';
  for (final entry in sections['header'] ?? const <String>[]) {
    if ((visited++ & 0xff) == 0) throwIfCancelled(cancelled);
    final separator = entry.indexOf(_unitSeparator);
    if (separator < 0 ||
        !equalsIgnoreCase(trimSpace(entry.substring(0, separator)), 'coordinate units')) {
      continue;
    }
    // A FlappedEar header extension, not a general VBO convention.
    final value = trimSpace(entry.substring(separator + 1)).toLowerCase();
    final declared = switch (value) {
      'degrees' => CoordinateUnit.degrees,
      'arc-minutes' => CoordinateUnit.arcMinutes,
      _ => null,
    };
    if (declared == null) {
      evidence.error = 'unsupported coordinate units declaration';
    } else if (evidence.unit != null && evidence.unit != declared) {
      evidence.error = 'conflicting coordinate unit evidence';
    } else {
      evidence.unit = declared;
      if (evidence.source.isEmpty) evidence.source = 'header-coordinate-units';
    }
  }
  if (evidence.unit == null && evidence.error.isEmpty) {
    evidence.error = 'no validated exporter or explicit coordinate units declaration';
  }
  if (evidence.error.isNotEmpty) {
    evidence.unit = null;
    evidence.source = 'unresolved';
  }
  return evidence;
}

/// A coordinate column value in degrees (NaN when invalid or the unit is
/// unknown); any other column's value unchanged.
double normalizeChannelValue(String name, double value, CoordinateUnit? unit) {
  final axis = coordinateAxisForName(name);
  if (axis == null) return value;
  if (unit == null) return double.nan;
  return normalizeCoordinateDegrees(axis, value, unit) ?? double.nan;
}

final class TimingGateParseResult {
  const TimingGateParseResult.gate(TimingGate this.gate) : error = '';
  const TimingGateParseResult.error(this.error) : gate = null;

  final TimingGate? gate;
  final String error;
}

// Five white-space separated tokens and an optional description. White space
// here is ASCII only.
final RegExp _gateLine = RegExp(
  r'^([^\t\n\x0B\f\r ]+)[\t\n\x0B\f\r ]+([^\t\n\x0B\f\r ]+)[\t\n\x0B\f\r ]+'
  r'([^\t\n\x0B\f\r ]+)[\t\n\x0B\f\r ]+([^\t\n\x0B\f\r ]+)[\t\n\x0B\f\r ]+'
  r'([^\t\n\x0B\f\r ]+)(?:[\t\n\x0B\f\r ]+(.*))?$',
);

const double _metersPerDegree = earthRadiusMeters * math.pi / 180.0;

/// Reads a `[laptiming]` line: name, longitude A, latitude A, longitude B,
/// latitude B, then an optional description.
///
/// With [centreDirection] (RaceChrono Pro 10.2.4), A is the gate centre and
/// A→B points backward along the direction of travel with the length of the
/// whole gate. The gate is rebuilt across that direction, half on each side.
TimingGateParseResult parseTimingGate(String line, bool centreDirection, CoordinateUnit unit) {
  final match = _gateLine.firstMatch(line);
  if (match == null) {
    return const TimingGateParseResult.error('expected a gate name and four coordinates');
  }
  final sourceName = match[1]!;
  if (sourceName.length > VboLimits.maximumFieldCharacters) {
    return const TimingGateParseResult.error('gate name exceeds the supported field limit');
  }
  final description = trimSpace(match[6] ?? '');
  if (description.length > VboLimits.maximumGateDescriptionCharacters) {
    return const TimingGateParseResult.error('gate description exceeds 4096 characters');
  }
  final source = List<double>.filled(4, 0.0);
  for (var index = 0; index < 4; ++index) {
    final token = match[index + 2]!;
    if (token.length > VboLimits.maximumFieldCharacters) {
      return const TimingGateParseResult.error('coordinate exceeds the supported field limit');
    }
    final value = parseDecimal(token);
    if (value == null || !value.isFinite) {
      return TimingGateParseResult.error('coordinate ${index + 1} is not finite');
    }
    source[index] = value;
  }
  final longitudeA = normalizeCoordinateDegrees(CoordinateAxis.longitude, source[0], unit);
  final latitudeA = normalizeCoordinateDegrees(CoordinateAxis.latitude, source[1], unit);
  final longitudeB = normalizeCoordinateDegrees(CoordinateAxis.longitude, source[2], unit);
  final latitudeB = normalizeCoordinateDegrees(CoordinateAxis.latitude, source[3], unit);
  if (longitudeA == null || latitudeA == null || longitudeB == null || latitudeB == null) {
    return const TimingGateParseResult.error('coordinate is outside the supported degree range');
  }
  var endpointA = GeoCoordinate(latitudeA, longitudeA);
  var endpointB = GeoCoordinate(latitudeB, longitudeB);
  if (endpointA == endpointB) {
    return const TimingGateParseResult.error('gate endpoints must be distinct');
  }
  if (centreDirection) {
    final vector = projectCoordinate(endpointB, endpointA);
    final width = hypot(vector.eastMeters, vector.northMeters);
    if (endpointA.latitudeDegrees.abs() >= 89.0 || width < 0.01 || width > 1000.0) {
      return const TimingGateParseResult.error('unsupported RaceChrono gate width or latitude');
    }
    // Rotate the backward vector by 90° in metric space and keep half of it on
    // each side of the centre.
    final deltaLat = vector.eastMeters * .5 / _metersPerDegree;
    final deltaLon =
        -vector.northMeters *
        .5 /
        (_metersPerDegree * math.cos(endpointA.latitudeDegrees * math.pi / 180.0));
    final centre = endpointA;
    endpointA = GeoCoordinate(
      centre.latitudeDegrees - deltaLat,
      centre.longitudeDegrees - deltaLon,
    );
    endpointB = GeoCoordinate(
      centre.latitudeDegrees + deltaLat,
      centre.longitudeDegrees + deltaLon,
    );
    if (!isValidCoordinate(endpointA) || !isValidCoordinate(endpointB)) {
      return const TimingGateParseResult.error('invalid converted RaceChrono gate endpoints');
    }
  }
  final lower = sourceName.toLowerCase();
  final type = lower == 'start'
      ? TimingGateType.start
      : lower == 'split'
      ? TimingGateType.split
      : TimingGateType.unknown;
  return TimingGateParseResult.gate(
    TimingGate(
      type: type,
      sourceName: sourceName,
      endpointA: endpointA,
      endpointB: endpointB,
      sourceDescription: description,
    ),
  );
}
