import 'dart:math' as math;

import 'package:telemetry_core/telemetry_core.dart';
import 'package:test/test.dart';

import 'support/sessions.dart';

void main() {
  test('converts arc-minute coordinates', () {
    final session = parse(
      '[header]\ncoordinate units = arc-minutes\n[column names]\n'
      'time latitude longitude\n[data]\n0 3120 -1260\n1 3126 -1266',
    );
    expect(session.channels['latitude']!.values[0], 52.0);
    expect(session.channels['longitude']!.values[0], -21.0);
  });

  group('resolves coordinate evidence', () {
    for (var format = 0; format < 3; ++format) {
      final cases = [
        for (final lat in [-0.25, 0.25])
          for (final lon in [-0.25, 0.25]) (lat, lon),
        (-0.00009, -0.00009),
        (52.0, 0.25),
      ];
      for (final (latitude, longitude) in cases) {
        test('format $format at $latitude, $longitude', () {
          final multiplier = format == 0 ? 1.0 : 60.0;
          String number(double degrees) => (degrees * multiplier).toStringAsFixed(10);
          final prefix = format == 2
              ? '[comments]\nGenerated by RaceChrono Pro v10.2.4\n'
              : '[HEADER]\nCoordinate Units : ${format == 0 ? 'Degrees' : 'Arc-Minutes'}\n'
                    'coordinate units = ${format == 0 ? 'Degrees' : 'Arc-Minutes'}\n';
          final text =
              '$prefix[laptiming]\nStart ${number(longitude)} ${number(latitude)} '
              '${number(longitude)} ${number(latitude + .00018)} synthetic\n'
              '[column names]\ntime lat long speed\n[data]\n'
              '0 ${number(latitude)} ${number(longitude)} 72\n'
              '1 ${number(latitude + .00018)} ${number(longitude + .00018)} 73\n';
          final session = parse(text);
          expect(session.warnings, isEmpty);
          expect(session.valueAt('latitude', 0), closeTo(latitude, 2e-6));
          expect(session.valueAt('longitude', 0), closeTo(longitude, 2e-6));
          expect(session.metadata['gpsCoordinateUnit'], format == 0 ? 'degrees' : 'arc-minutes');
          expect(
            session.metadata['gpsCoordinateEvidence'],
            format == 2 ? 'racechrono-pro-10.2.4' : 'header-coordinate-units',
          );
          expect(session.timingGates, hasLength(1));
          final gate = session.timingGates.single;
          if (format == 2) {
            expect(
              (gate.endpointA.latitudeDegrees + gate.endpointB.latitudeDegrees) / 2,
              closeTo(latitude, 1e-10),
            );
            expect(
              (gate.endpointA.longitudeDegrees + gate.endpointB.longitudeDegrees) / 2,
              closeTo(longitude, 1e-10),
            );
          } else {
            expect(gate.endpointA.latitudeDegrees, closeTo(latitude, 1e-10));
            expect(gate.endpointA.longitudeDegrees, closeTo(longitude, 1e-10));
            expect(gate.endpointB.latitudeDegrees, closeTo(latitude + .00018, 1e-10));
          }
          final width = projectCoordinate(gate.endpointB, gate.endpointA);
          expect(_length(width.eastMeters, width.northMeters), closeTo(20.0151, .01));
        });
      }
    }
  });

  group('withholds coordinates without trusted unit evidence', () {
    final prefixes = {
      'missing': '',
      'unknown exporter': '[comments]\nGenerated by Unknown v1\n',
      'unverified RaceChrono': '[comments]\nGenerated by RaceChrono Pro v99.0\n',
      'unsupported unit': '[header]\ncoordinate units = radians\n',
      'empty unit': '[header]\ncoordinate units =\n',
      'conflicting units': '[header]\ncoordinate units = degrees\ncoordinate units = arc-minutes\n',
      'invalid then valid': '[header]\ncoordinate units = radians\ncoordinate units = degrees\n',
      'exporter and unit conflict':
          '[comments]\nGenerated by RaceChrono Pro v10.2.4\n[header]\ncoordinate units = degrees\n',
      'conflicting exporters':
          '[comments]\nGenerated by RaceChrono Pro v10.2.4\n'
          'Generated by Unknown v1\n[header]\ncoordinate units = arc-minutes\n',
      'reverse exporter conflict':
          '[comments]\nGenerated by Unknown v1\nGenerated by RaceChrono Pro v10.2.4\n',
      'spoofed derived metadata':
          '[header]\ngpsCoordinateUnit = degrees\n'
          'gpsCoordinateEvidence = racechrono-pro-10.2.4\ntimingGateFormat = fake\n'
          'gpsLongitudeConvention = west-positive\n',
    };
    prefixes.forEach((name, prefix) {
      test(name, () {
        final session = parse(
          '$prefix[laptiming]\nStart 15 15 15 15.01 ambiguous\n'
          '[column names]\ntime latitude longitude speed\n[data]\n0 15 15 72\n1 3120 1260 73\n',
        );
        expect(session.sampleCount, 2);
        expect(session.valueAt('speed', 0), 72.0);
        expect(session.valueAt('speed', 1), 73.0);
        expect(session.valueAt('latitude', 0), isNull);
        expect(session.valueAt('longitude', 1), isNull);
        expect(session.timingGates, isEmpty);
        expect(session.metadata['gpsCoordinateUnit'], 'unresolved');
        expect(session.metadata['gpsCoordinateEvidence'], 'unresolved');
        expect(session.metadata.containsKey('timingGateFormat'), isFalse);
        expect(session.metadata.containsKey('gpsLongitudeConvention'), isFalse);
        expect(
          session.warnings.join(' '),
          contains('GPS coordinates and timing gates unavailable'),
        );
      });
    });
  });

  test('validates declared coordinate bounds', () {
    for (final unit in CoordinateUnit.values) {
      final multiplier = unit == CoordinateUnit.degrees ? 1.0 : 60.0;
      for (final sign in [-1.0, 1.0]) {
        expect(
          normalizeCoordinateDegrees(CoordinateAxis.latitude, sign * 90 * multiplier, unit),
          sign * 90,
        );
        expect(
          normalizeCoordinateDegrees(CoordinateAxis.longitude, sign * 180 * multiplier, unit),
          sign * 180,
        );
        expect(
          normalizeCoordinateDegrees(CoordinateAxis.latitude, sign * 91 * multiplier, unit),
          isNull,
        );
        expect(
          normalizeCoordinateDegrees(CoordinateAxis.longitude, sign * 181 * multiplier, unit),
          isNull,
        );
      }
      expect(normalizeCoordinateDegrees(CoordinateAxis.latitude, double.nan, unit), isNull);
      expect(normalizeCoordinateDegrees(CoordinateAxis.longitude, double.infinity, unit), isNull);
    }
    final session = parse(
      '[header]\ncoordinate units = degrees\n[laptiming]\n'
      'Start 15 91 15 89 invalid\n[column names]\ntime latitude longitude speed\n'
      '[data]\n0 0 0 72\n1 91 181 73\n',
    );
    expect(session.valueAt('latitude', 1), isNull);
    expect(session.valueAt('longitude', 1), isNull);
    expect(session.timingGates, isEmpty);
  });

  test('parses timing gates up to the limit of 128', () {
    final parsed = parse(
      '[header]\ncoordinate units = degrees\n[laptiming]\n'
      'Start 21.0000 52.0000 21.0000 52.0002 main straight\n'
      'Split 21.1000 52.1000 21.1000 52.1002 sector one\n'
      'Start malformed gate\n'
      '[column names]\ntime latitude longitude\n[data]\n0 52.0 21.0\n1 52.0001 21.0001\n',
    );
    expect(parsed.timingGates, hasLength(2));
    expect(parsed.timingGates[0].type, TimingGateType.start);
    expect(parsed.timingGates[0].sourceDescription, 'main straight');
    expect(parsed.timingGates[1].type, TimingGateType.split);
    expect(parsed.warnings.any((w) => w.contains('Timing line 3 ignored')), isTrue);

    final bounded = StringBuffer('[header]\ncoordinate units = degrees\n[laptiming]\n');
    for (var index = 0; index < 129; ++index) {
      bounded.write('Start 21.0000 52.0000 21.0000 52.0002 gate $index\n');
    }
    bounded.write('[column names]\ntime latitude longitude\n[data]\n0 52.0 21.0\n');
    final limited = parse(bounded.toString());
    expect(limited.timingGates, hasLength(128));
    expect(limited.warnings.any((w) => w.contains('supported limit of 128')), isTrue);
  });

  test('derives the UTC start only from a validated RaceChrono export', () {
    final session = parseVboFile('test/parity/corpus/racechrono_10_2_4.vbo');
    // 19 August 2026, first sample at 11:14:28 UTC.
    expect(
      session.metadata['firstTimestampMilliseconds'],
      DateTime.utc(2026, 8, 19, 11, 14, 28).millisecondsSinceEpoch.toString(),
    );
    expect(session.metadata['gpsLongitudeConvention'], 'west-positive');
    final relative = parse(
      'File created on 19/08/2026 at 11:20:05\n'
      '[comments]\nGenerated by RaceChrono Pro v10.2.4\n[column names]\ntime a\n[data]\n0 1\n1 2\n',
    );
    expect(relative.metadata.containsKey('firstTimestampMilliseconds'), isFalse);
  });
}

double _length(double x, double y) => math.sqrt(x * x + y * y);
