import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';
import 'package:fetproject/fetproject.dart';
import 'package:test/test.dart';

// Vectors generated by FlappedEar Overlays' own functions (Qt 6.8.3); see
// test/fixtures/README.md.
final Map<String, Object?> vectors = (jsonDecode(
  File('test/fixtures/qt_hash_vectors.json').readAsStringSync(),
) as Map).cast<String, Object?>();

List<Map<String, Object?>> cases(String name) => [
  for (final item in vectors[name] as List)
    (item as Map).cast<String, Object?>(),
];

double fromBits(String hex) {
  final bytes = ByteData(8)
    ..setUint32(0, int.parse(hex.substring(0, 8), radix: 16))
    ..setUint32(4, int.parse(hex.substring(8), radix: 16));
  return bytes.getFloat64(0);
}

void main() {
  group('round trip through the Qt parser and writer', () {
    for (final vector in cases('roundTrips')) {
      test(vector['name'], () {
        final value = qtJsonDecode(vector['json'] as String);
        expect(qtCompactJson(value), vector['compact']);
        expect(
          sha256.convert(qtCompactJsonBytes(value)).toString(),
          vector['sha256'],
        );
      });
    }
  });

  test('every double formats as Qt formats it', () {
    final doubles = cases('doubles');
    expect(doubles.length, greaterThan(1000));
    for (final vector in doubles) {
      final value = fromBits(vector['bits'] as String);
      expect(
        '[${qtFormatDouble(value)}]',
        vector['compact'],
        reason: 'bits ${vector['bits']} ($value)',
      );
    }
  });

  test('non-finite values are written as null', () {
    expect(
      qtCompactJson([double.nan, double.infinity, -double.infinity]),
      '[null,null,null]',
    );
  });

  test('keys sort by code point', () {
    final keys = ['b', 'a', '\u{1F3C1}', '￿', 'Z']..sort(compareByCodePoint);
    expect(keys, ['Z', 'a', 'b', '￿', '\u{1F3C1}']);
  });

  test('an unsupported value is refused', () {
    expect(() => qtCompactJson(DateTime(2026)), throwsArgumentError);
  });

  group('nesting depth', () {
    String nested(int depth, {String leaf = '0'}) =>
        '${'[' * depth}$leaf${']' * depth}';

    test('is limited before the value is walked, however deep the text', () {
      expect(
        () => qtJsonDecode(nested(1000000), maxDepth: 32),
        throwsA(isA<QtJsonDepthException>()),
      );
      expect(
        () => qtJsonDecode(nested(100000)),
        throwsA(isA<QtJsonDepthException>()),
      );
    });

    test('allows exactly maxDepth levels and refuses one more', () {
      expect(qtJsonDecode(nested(32), maxDepth: 32), isA<List>());
      expect(
        () => qtJsonDecode(nested(33), maxDepth: 32),
        throwsA(isA<QtJsonDepthException>()),
      );
      // Empty containers: the innermost one is at level 32.
      expect(qtJsonDecode('${'[' * 33}${']' * 33}', maxDepth: 32), isA<List>());
      expect(
        () => qtJsonDecode('${'[' * 34}${']' * 34}', maxDepth: 32),
        throwsA(isA<QtJsonDepthException>()),
      );
    });

    test('brackets inside strings do not count', () {
      expect(
        qtJsonDecode('{"a":"${'[' * 500}\\"${'{' * 500}"}', maxDepth: 4),
        isA<Map>(),
      );
    });

    test('numbers are still normalised within the limit', () {
      expect(qtJsonDecode('[1.0,{"a":2e0,"b":0.5}]', maxDepth: 4), [
        1,
        {'a': 2, 'b': 0.5},
      ]);
    });
  });
}
