// The weather of a day's sessions: looked up once per recording, kept
// with the day and shown per session. Synthetic recordings and a made-up
// weather service only; nothing is sent anywhere.
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:telemetry/day/day_results_controller.dart';
import 'package:telemetry/day/day_results_page.dart';
import 'package:telemetry/day/day_weather.dart';
import 'package:telemetry/day/weather_text.dart';
import 'package:telemetry/import/import_runner.dart';
import 'package:telemetry/l10n/app_localizations_en.dart';
import 'package:telemetry/main.dart';
import 'package:telemetry/profile/profile_library.dart';
import 'package:telemetry/settings_dialog.dart';
import 'package:telemetry/units.dart';
import 'package:telemetry_core/telemetry_core.dart';

import 'day_results_page_test.dart' show FakeDocuments, circuitVbo;

final class _SyncAppender implements DayAppender {
  @override
  DayAppendJob start(DayAppendRequest request, void Function(int, int) _) =>
      _SyncJob(runDayAppend(request));
}

final class _SyncJob implements DayAppendJob {
  _SyncJob(DayAppendOutcome outcome) : result = Future.value(outcome);

  @override
  final Future<DayAppendOutcome> result;

  @override
  void cancel() {}
}

/// A made-up weather service: every hour of the days asked for, 18 °C,
/// overcast, no rain, wind from the south-west at 12 km/h.
final class _Service {
  final asked = <Uri>[];
  bool offline = false;
  Completer<void>? gate;

  Future<Object?> fetch(Uri uri) async {
    asked.add(uri);
    await gate?.future;
    if (offline) throw const SocketException('offline');
    final start = DateTime.parse('${uri.queryParameters['start_date']}T00:00Z');
    final end = DateTime.parse('${uri.queryParameters['end_date']}T00:00Z');
    final hours = (end.difference(start).inHours) + 24;
    List<Object?> series(Object? value) => List.filled(hours, value);
    return {
      'hourly': {
        'time': [
          for (var h = 0; h < hours; ++h)
            start.add(Duration(hours: h)).toIso8601String().substring(0, 16),
        ],
        'temperature_2m': series(18.0),
        'relative_humidity_2m': series(70.0),
        'precipitation': series(0.0),
        'weather_code': series(3),
        'cloud_cover': series(90.0),
        'surface_pressure': series(1012.0),
        'wind_speed_10m': series(12.0),
        'wind_direction_10m': series(225.0),
        'wind_gusts_10m': series(25.0),
      },
    };
  }
}

/// [circuitVbo] as RaceChrono exports it, recorded from 10:15:00 UTC on
/// 29 August 2026 (synthetic).
String _datedVbo(List<double> speeds) {
  final text = circuitVbo(speeds);
  final data = text.indexOf('[data]\n') + '[data]\n'.length;
  String two(int value) => value.toString().padLeft(2, '0');
  final rows = [
    for (final row in text.substring(data).trim().split('\n'))
      () {
        final fields = row.split(' ');
        final seconds = 10 * 3600 + 15 * 60 + double.parse(fields.first);
        final whole = seconds.floor();
        final clock =
            '${two(whole ~/ 3600)}${two(whole ~/ 60 % 60)}${two(whole % 60)}'
            '.${((seconds - whole) * 100).round().toString().padLeft(2, '0')}';
        // RaceChrono writes minutes, west positive.
        final latitude = double.parse(fields[1]) * 60;
        final longitude = -double.parse(fields[2]) * 60;
        return [
          clock,
          latitude.toStringAsFixed(6),
          longitude.toStringAsFixed(6),
          ...fields.skip(3),
        ].join(' ');
      }(),
  ];
  return 'File created on 29/08/2026 at 10:15:00\n'
      '[comments]\nGenerated by RaceChrono Pro v10.2.4\n'
      '${text.substring(0, data).replaceFirst('[header]\ncoordinate units = degrees\n', '')}'
      '${rows.join('\n')}\n';
}

/// Counts the days recorded in the profile, and the weather given to it.
final class _CountingLibrary extends ProfileLibrary {
  _CountingLibrary(String folder)
    : super(
        store: FolderProfileStore(folder),
        defaultCarName: 'My car',
        defaultTrackName: (number) => 'Track $number',
        background: <R>(FutureOr<R> Function() computation) async =>
            computation(),
      );

  final recorded = <Map<String, ProfileWeather?>?>[];
  final weatherRecorded = <Map<String, ProfileWeather>>[];

  @override
  void recordWeather(String eventId, Map<String, ProfileWeather> weather) {
    weatherRecorded.add(weather);
    super.recordWeather(eventId, weather);
  }

  @override
  Future<void> recordDay({
    required String eventId,
    required String path,
    required String name,
    required DayAnalysis analysis,
    Map<String, TelemetrySession?>? recordings,
    DayTheoreticalBest? theoreticalBest,
    Map<String, ProfileWeather?>? weather,
  }) {
    recorded.add(weather);
    return super.recordDay(
      eventId: eventId,
      path: path,
      name: name,
      analysis: analysis,
      recordings: recordings,
      theoreticalBest: theoreticalBest,
      weather: weather,
    );
  }
}

void main() {
  late Directory directory;
  setUp(() => directory = Directory.systemTemp.createTempSync('weather'));
  tearDown(() => directory.deleteSync(recursive: true));

  String write(String name, List<double> speeds, {bool dated = true}) {
    final path = '${directory.path}/$name';
    File(path)
        .writeAsStringSync(dated ? _datedVbo(speeds) : circuitVbo(speeds));
    return path;
  }

  DayImportOutcome importDay(List<String> paths) =>
      runDayImport((paths: paths, includeSubfolders: false));

  Map<String, Object?> documentRun(Map<String, Object?> document, String id) =>
      ((document['event']! as Map)['runs']! as List)
          .cast<Map<String, Object?>>()
          .firstWhere((run) => run['id'] == id);

  Future<void> settle() async {
    for (var i = 0; i < 10; ++i) {
      await Future<void>.delayed(Duration.zero);
    }
  }

  group('DayWeather', () {
    test(
      'asks once per session with only the rounded position and date',
      () async {
        final day = importDay([
          write('a.vbo', [30, 28]),
          write('b.vbo', [29]),
        ]);
        final service = _Service();
        final weather = DayWeather(fetcher: service.fetch);
        addTearDown(weather.dispose);
        final fetched = <String>[];
        weather.onFetched = fetched.add;
        weather.sync(day.runs, const []);
        expect(
          weather.stateOf(day.runs.first.run.id),
          SessionWeatherState.fetching,
        );
        await settle();
        expect(service.asked, hasLength(2));
        for (final uri in service.asked) {
          expect(uri.host, 'archive-api.open-meteo.com');
          expect(uri.queryParameters['latitude'], '52.00');
          expect(uri.queryParameters['longitude'], '21.00');
          expect(uri.queryParameters['start_date'], '2026-08-29');
        }
        expect(fetched, [for (final named in day.runs) named.run.id]);
        final first = weather.of(day.runs.first.run.id)!;
        expect(first.sourceRevision, day.runs.first.run.contentSha256);
        expect(first.summary.temperatureC, 18);
        expect(weather.fetched.keys, unorderedEquals(fetched));
        // Synced again, nothing is asked twice.
        weather.sync(day.runs, const []);
        await settle();
        expect(service.asked, hasLength(2));
      },
    );

    test(
      'shows the stored weather of the same recording without asking',
      () async {
        final day = importDay([
          write('a.vbo', [30, 28]),
        ]);
        final run = day.runs.single.run;
        final service = _Service();
        final first = DayWeather(fetcher: service.fetch);
        addTearDown(first.dispose);
        first.sync(day.runs, const []);
        await settle();
        final stored = first.of(run.id)!;
        final weather = DayWeather(fetcher: service.fetch);
        addTearDown(weather.dispose);
        weather.sync(day.runs, [
          {'id': run.id, sessionWeatherKey: stored.toJson()},
        ]);
        await settle();
        expect(service.asked, hasLength(1));
        expect(weather.of(run.id)?.toJson(), stored.toJson());
        expect(weather.fetched, isEmpty);
      },
    );

    test(
      'asks again for a replaced recording, never over a newer version',
      () async {
        final day = importDay([
          write('a.vbo', [30, 28]),
        ]);
        final run = day.runs.single.run;
        final service = _Service();
        final weather = DayWeather(fetcher: service.fetch);
        addTearDown(weather.dispose);
        final other = SessionWeather(
          sourceRevision: 'f' * 64,
          latitude: 52,
          longitude: 21,
          startMilliseconds: 0,
          endMilliseconds: 1000,
          fetchedMilliseconds: 0,
          hours: const [],
        );
        weather.sync(day.runs, [
          {'id': run.id, sessionWeatherKey: other.toJson()},
        ]);
        await settle();
        expect(service.asked, hasLength(1));
        expect(weather.of(run.id)!.sourceRevision, run.contentSha256);

        final newer = DayWeather(fetcher: service.fetch);
        addTearDown(newer.dispose);
        newer.sync(day.runs, [
          {
            'id': run.id,
            sessionWeatherKey: {'version': 'session-weather-v2'},
          },
        ]);
        await settle();
        expect(service.asked, hasLength(1));
        expect(newer.stateOf(run.id), SessionWeatherState.kept);
      },
    );

    test('offline: unavailable until asked again', () async {
      final day = importDay([
        write('a.vbo', [30, 28]),
      ]);
      final id = day.runs.single.run.id;
      final service = _Service()..offline = true;
      final weather = DayWeather(fetcher: service.fetch);
      addTearDown(weather.dispose);
      weather.sync(day.runs, const []);
      await settle();
      expect(weather.stateOf(id), SessionWeatherState.unavailable);
      weather.sync(day.runs, const []);
      await settle();
      expect(service.asked, hasLength(1));
      service.offline = false;
      weather.retry(id);
      await settle();
      expect(service.asked, hasLength(2));
      expect(weather.stateOf(id), SessionWeatherState.ready);
    });

    test(
      'offline at the track: the next session added asks again for all',
      () async {
        final day = importDay([
          write('a.vbo', [30, 28]),
          write('b.vbo', [31, 29]),
        ]);
        final first = day.runs.first;
        final second = day.runs.last;
        final service = _Service()..offline = true;
        final weather = DayWeather(fetcher: service.fetch);
        addTearDown(weather.dispose);
        weather.sync([first], const []);
        await settle();
        expect(weather.stateOf(first.run.id), SessionWeatherState.unavailable);
        // The same sessions again (a reopened lap, an edit): not asked again.
        weather.sync([first], const []);
        await settle();
        expect(service.asked, hasLength(1));
        // Signal back, and the next session is shared: both get weather.
        service.offline = false;
        weather.sync([first, second], const []);
        await settle();
        expect(service.asked, hasLength(3));
        expect(weather.stateOf(first.run.id), SessionWeatherState.ready);
        expect(weather.stateOf(second.run.id), SessionWeatherState.ready);
      },
    );

    test('nothing is asked while off, nor for an undated recording', () async {
      final day = importDay([
        write('a.vbo', [30, 28]),
        write('b.vbo', [29], dated: false),
      ]);
      final service = _Service();
      final enabled = ValueNotifier(false);
      final weather = DayWeather(fetcher: service.fetch, enabled: enabled);
      addTearDown(weather.dispose);
      weather.sync(day.runs, const []);
      await settle();
      expect(service.asked, isEmpty);
      final dated = day.runs.firstWhere(
        (named) => recordingTimestamp(named.run.telemetry) != null,
      );
      final undated = day.runs.firstWhere((named) => named != dated);
      expect(weather.stateOf(dated.run.id), SessionWeatherState.off);
      expect(weather.stateOf(undated.run.id), SessionWeatherState.none);
      enabled.value = true;
      await settle();
      expect(service.asked, hasLength(1));
      expect(weather.stateOf(dated.run.id), SessionWeatherState.ready);
    });
  });

  group('the day', () {
    test(
      'saves fetched weather with the day without making it unsaved',
      () async {
        final path = '${directory.path}/Day.fetproject';
        final first = importDay([
          write('a.vbo', [30, 28]),
        ]);
        final saving = DayResultsController(
          runs: first.runs,
          analysis: first.analysis!,
          writer: saveDayDocument,
          weather: DayWeather(fetcher: _Service().fetch),
        );
        await settle();
        await saving.save(path);
        saving.dispose();
        final id = first.runs.single.run.id;
        final saved = openDay(path);
        expect(
          SessionWeather.fromJson(
            documentRun(saved.document, id)[sessionWeatherKey],
          )?.summary.temperatureC,
          18,
        );

        // Opened again: the stored weather shows and nothing is asked.
        final service = _Service();
        final opened = DayResultsController.opened(
          saved,
          writer: saveDayDocument,
          weather: DayWeather(fetcher: service.fetch),
        );
        addTearDown(opened.dispose);
        await settle();
        expect(service.asked, isEmpty);
        expect(opened.weather.of(id), isNotNull);
        expect(opened.dirty, isFalse);
      },
    );

    test(
      'a session added to a saved day is saved again with its weather',
      () async {
        final path = '${directory.path}/Day.fetproject';
        final first = importDay([
          write('a.vbo', [30, 28]),
        ]);
        final service = _Service()..offline = true;
        final controller = DayResultsController(
          runs: first.runs,
          analysis: first.analysis!,
          writer: saveDayDocument,
          appender: _SyncAppender(),
          weather: DayWeather(fetcher: service.fetch),
        );
        addTearDown(controller.dispose);
        await settle();
        await controller.save(path);
        service
          ..offline = false
          ..gate = Completer<void>();
        final addition = await controller.addRecordings([
          write('b.vbo', [29, 31]),
        ]);
        expect(addition.savedTo, path);
        final added = controller.runs.last.run.id;
        expect(
          documentRun(
            openDay(path).document,
            added,
          ).containsKey(sessionWeatherKey),
          isFalse,
        );
        // The weather arrives after the addition was saved.
        service.gate!.complete();
        await settle();
        while (controller.saving) {
          await settle();
        }
        expect(
          documentRun(openDay(path).document, added)[sessionWeatherKey],
          isNotNull,
        );
        expect(controller.dirty, isFalse);
      },
    );
  });

  test('weather reads as words', () {
    final l10n = AppLocalizationsEn();
    expect(compassPoint(225), 'SW');
    expect(compassPoint(359), 'N');
    expect(compassPoint(23), 'NE');
    final weather = SessionWeather(
      sourceRevision: 'a' * 64,
      latitude: 52,
      longitude: 21,
      startMilliseconds: DateTime.utc(
        2026,
        8,
        29,
        10,
        15,
      ).millisecondsSinceEpoch,
      endMilliseconds: DateTime.utc(2026, 8, 29, 10, 45).millisecondsSinceEpoch,
      fetchedMilliseconds: 0,
      hours: [
        WeatherHour(
          time: DateTime.utc(2026, 8, 29, 10).millisecondsSinceEpoch,
          temperatureC: 17.6,
          windSpeedKmh: 11.6,
          windDirectionDegrees: 220,
          weatherCode: 3,
          precipitationMm: 0,
        ),
        WeatherHour(
          time: DateTime.utc(2026, 8, 29, 11).millisecondsSinceEpoch,
          temperatureC: 18.2,
          windSpeedKmh: 12.4,
          windDirectionDegrees: 230,
          weatherCode: 61,
          precipitationMm: 0.4,
        ),
      ],
    );
    expect(
      weatherShortText(l10n, weather),
      '18 °C, rain, 0.4 mm of rain, wind SW 12 km/h',
    );
  });

  testWidgets('shows each session\'s weather and its source', (tester) async {
    final day = importDay([
      write('a.vbo', [30, 28, 31]),
      write('b.vbo', [29, 32]),
    ]);
    final controller = DayResultsController(
      runs: day.runs,
      analysis: day.analysis!,
      weather: DayWeather(fetcher: _Service().fetch),
    );
    await tester.binding.setSurfaceSize(const Size(1200, 6000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await tester.pumpWidget(
      TelemetryApp(
        home: DayResultsPage.controller(
          controller: controller,
          documents: FakeDocuments(location: '${directory.path}/d.fetproject'),
        ),
      ),
    );
    await tester.runAsync(settle);
    await tester.pumpAndSettle();
    const line = 'Weather: 18 °C, overcast, no rain, wind SW 12 km/h';
    expect(find.textContaining(line), findsWidgets);
    expect(find.textContaining('Weather data by Open-Meteo.com'), findsWidgets);

    await tester.tap(
      find.byKey(ValueKey('sessionDetails ${day.runs.first.run.id}')),
    );
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('sessionWeather')), findsOneWidget);
    expect(find.text('air 18 °C'), findsOneWidget);
    expect(find.text('gusts up to 25 km/h'), findsOneWidget);
    expect(find.text('humidity 70%'), findsOneWidget);
  });

  testWidgets('the lookup can be turned off in settings', (tester) async {
    addTearDown(() => weatherLookupSetting.value = true);
    await tester.pumpWidget(const TelemetryApp(home: SettingsButton()));
    await tester.tap(find.byType(SettingsButton));
    await tester.pumpAndSettle();
    expect(find.textContaining('rounded to about 1 km'), findsOneWidget);
    // Below the look settings, so scrolled to first.
    await tester.ensureVisible(
      find.byKey(const ValueKey('weatherLookupSetting')),
    );
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const ValueKey('weatherLookupSetting')));
    await tester.pump();
    expect(weatherLookupSetting.value, isFalse);
  });

  group('review fixes', () {
    test(
      'weather fetched before the history was final is fetched again later',
      () async {
        final day = importDay([
          write('a.vbo', [30, 28]),
        ]);
        final run = day.runs.single.run;
        final end = DateTime.utc(2026, 8, 29, 11).millisecondsSinceEpoch;
        const days5 = 5 * 24 * 3600 * 1000;
        final service = _Service();
        final early = DayWeather(fetcher: service.fetch, clock: () => end);
        addTearDown(early.dispose);
        early.sync(day.runs, const []);
        await settle();
        final stored = early.of(run.id)!;
        expect(stored.preliminary, isTrue);
        // Opened again within five days: shown, not asked again.
        final soon = DayWeather(
          fetcher: service.fetch,
          clock: () => end + days5 ~/ 2,
        );
        addTearDown(soon.dispose);
        soon.sync(day.runs, [
          {'id': run.id, sessionWeatherKey: stored.toJson()},
        ]);
        await settle();
        expect(service.asked, hasLength(1));
        expect(soon.fetched, isEmpty);
        // Opened after five days: shown, and asked once more.
        final later = DayWeather(
          fetcher: service.fetch,
          clock: () => end + 2 * days5,
        );
        addTearDown(later.dispose);
        later.sync(day.runs, [
          {'id': run.id, sessionWeatherKey: stored.toJson()},
        ]);
        expect(later.of(run.id), isNotNull);
        await settle();
        expect(service.asked, hasLength(2));
        expect(later.fetched[run.id]!.preliminary, isFalse);
        // The final weather is not asked for again.
        final last = DayWeather(
          fetcher: service.fetch,
          clock: () => end + 3 * days5,
        );
        addTearDown(last.dispose);
        last.sync(day.runs, [
          {'id': run.id, sessionWeatherKey: later.fetched[run.id]!.toJson()},
        ]);
        await settle();
        expect(service.asked, hasLength(2));
      },
    );

    test(
      'an answer arriving after the lookup was turned off is dropped',
      () async {
        final day = importDay([
          write('a.vbo', [30, 28]),
        ]);
        final id = day.runs.single.run.id;
        final service = _Service()..gate = Completer<void>();
        final enabled = ValueNotifier(true);
        final weather = DayWeather(fetcher: service.fetch, enabled: enabled);
        addTearDown(weather.dispose);
        weather.sync(day.runs, const []);
        await settle();
        expect(service.asked, hasLength(1));
        enabled.value = false;
        service.gate!.complete();
        await settle();
        expect(weather.of(id), isNull);
        expect(weather.fetched, isEmpty);
        expect(weather.stateOf(id), SessionWeatherState.off);
      },
    );

    test(
      'an answer for a replaced recording or after the day closed is dropped',
      () async {
        final a = importDay([
          write('a.vbo', [30, 28]),
        ]);
        final b = importDay([
          write('b.vbo', [29, 31]),
        ]);
        final service = _Service()..gate = Completer<void>();
        final weather = DayWeather(fetcher: service.fetch);
        addTearDown(weather.dispose);
        weather.sync(a.runs, const []);
        await settle();
        // The same session now reads another recording.
        final id = a.runs.single.run.id;
        final other = b.runs.single.run;
        final swapped = [
          (
            run: TelemetryRunProposal(
              id: id,
              sourceId: other.sourceId,
              sourcePath: other.sourcePath,
              format: other.format,
              contentSha256: other.contentSha256,
              telemetry: other.telemetry,
              laps: other.laps,
            ),
            name: a.runs.single.name,
          ),
        ];
        weather.sync(swapped, const []);
        service.gate!.complete();
        await settle();
        expect(weather.of(id)!.sourceRevision, other.contentSha256);
        expect(service.asked, hasLength(2));

        final closing = DayWeather(fetcher: _Service().fetch);
        var fetched = 0;
        closing.onFetched = (_) => ++fetched;
        closing.sync(a.runs, const []);
        closing.dispose();
        await settle();
        expect(fetched, 0);
      },
    );

    test('a weather of a newer version survives a save', () async {
      final path = '${directory.path}/Day.fetproject';
      final first = importDay([
        write('a.vbo', [30, 28]),
      ]);
      final id = first.runs.single.run.id;
      final saving = DayResultsController(
        runs: first.runs,
        analysis: first.analysis!,
        writer: saveDayDocument,
        weather: DayWeather(),
      );
      await saving.save(path);
      saving.dispose();
      final document = openDay(path).document;
      documentRun(document, id)[sessionWeatherKey] = {
        'version': 'session-weather-v2',
        'future': [1, 2],
      };
      await saveDayDocument(path, document);
      final service = _Service();
      final opened = DayResultsController.opened(
        openDay(path),
        writer: saveDayDocument,
        weather: DayWeather(fetcher: service.fetch),
      );
      addTearDown(opened.dispose);
      await settle();
      expect(service.asked, isEmpty);
      expect(opened.weather.stateOf(id), SessionWeatherState.kept);
      await opened.save(path);
      expect(documentRun(openDay(path).document, id)[sessionWeatherKey], {
        'version': 'session-weather-v2',
        'future': [1, 2],
      });
    });

    test('weather arriving while the day has unsaved edits waits for the next save', () async {
      final path = '${directory.path}/Day.fetproject';
      final first = importDay([
        write('a.vbo', [30, 28]),
      ]);
      final service = _Service()..offline = true;
      final controller = DayResultsController(
        runs: first.runs,
        analysis: first.analysis!,
        writer: saveDayDocument,
        appender: _SyncAppender(),
        weather: DayWeather(fetcher: service.fetch),
      );
      addTearDown(controller.dispose);
      await settle();
      await controller.save(path);
      service
        ..offline = false
        ..gate = Completer<void>();
      await controller.addRecordings([
        write('b.vbo', [29, 31]),
      ]);
      final added = controller.runs.last.run.id;
      expect(controller.renameDay('Not saved yet'), isNull);
      expect(controller.dirty, isTrue);
      service.gate!.complete();
      await settle();
      expect(controller.weather.of(added), isNotNull);
      final saved = openDay(path);
      expect(saved.name, isNot('Not saved yet'));
      expect(
        documentRun(saved.document, added).containsKey(sessionWeatherKey),
        isFalse,
      );
      await controller.save(path);
      expect(
        documentRun(openDay(path).document, added)[sessionWeatherKey],
        isNotNull,
      );
    });
  });

  testWidgets(
    'weather arriving after the day was saved goes to the profile, once',
    (tester) async {
      final day = importDay([
        write('a.vbo', [30, 28, 31]),
      ]);
      final id = day.runs.single.run.id;
      final service = _Service()..gate = Completer<void>();
      final controller = DayResultsController(
        runs: day.runs,
        analysis: day.analysis!,
        weather: DayWeather(fetcher: service.fetch),
      );
      final library = _CountingLibrary('${directory.path}/Profile');
      await tester.pumpWidget(
        TelemetryApp(
          home: DayResultsPage.controller(
            controller: controller,
            documents: FakeDocuments(
              location: '${directory.path}/d.fetproject',
            ),
            library: library,
          ),
        ),
      );
      ProfileSession? session() =>
          library.profile?.day(controller.eventId)?.sessions.firstOrNull;
      Future<void> until(bool Function() done) async {
        for (var i = 0; i < 200 && !done(); ++i) {
          await tester.runAsync(
            () => Future<void>.delayed(const Duration(milliseconds: 10)),
          );
          await tester.pump();
        }
        expect(done(), isTrue);
      }

      // Saved in the library and recorded before the weather arrives.
      await until(() => session() != null);
      expect(session()!.weather, isNull);
      final before = library.recorded.length;
      expect(library.recorded.last?[id], isNull);

      service.gate!.complete();
      await until(() => session()?.weather != null);
      expect(session()!.weather!.temperatureC, 18);
      expect(session()!.weather!.condition, WeatherCondition.overcast);
      // Only the weather is given: the day is not measured again.
      expect(library.recorded.length, before);
      expect(library.weatherRecorded, hasLength(1));
      expect(
        library.weatherRecorded.single[id]!.sourceRevision,
        day.runs.single.run.contentSha256,
      );

      // Told again with nothing new: not given again.
      controller.weather.retry(id);
      await tester.runAsync(settle);
      await tester.pump();
      expect(library.recorded.length, before);
      expect(library.weatherRecorded, hasLength(1));

      // Written to the profile's file, as the card reads it.
      final file = File('${directory.path}/Profile/$profileFileName');
      ProfileWeather? written() => file.existsSync()
          ? decodeDriverProfile(file.readAsStringSync())
                .day(controller.eventId)
                ?.sessions
                .single
                .weather
          : null;
      await until(() => written() != null);
      expect(written()!.windSpeedKmh, 12);
      await tester.pumpWidget(const SizedBox());
      await tester.pump(const Duration(seconds: 3));
    },
  );

  testWidgets(
    'weather arriving on a day with unsaved changes goes with the save',
    (tester) async {
      final day = importDay([
        write('a.vbo', [30, 28, 31]),
      ]);
      final id = day.runs.single.run.id;
      final service = _Service()..gate = Completer<void>();
      final controller = DayResultsController(
        runs: day.runs,
        analysis: day.analysis!,
        weather: DayWeather(fetcher: service.fetch),
      );
      final library = _CountingLibrary('${directory.path}/Profile');
      await tester.pumpWidget(
        TelemetryApp(
          home: DayResultsPage.controller(
            controller: controller,
            documents: FakeDocuments(
              location: '${directory.path}/d.fetproject',
            ),
            library: library,
          ),
        ),
      );
      Future<void> until(bool Function() done) async {
        for (var i = 0; i < 300 && !done(); ++i) {
          await tester.runAsync(
            () => Future<void>.delayed(const Duration(milliseconds: 10)),
          );
          await tester.pump(const Duration(milliseconds: 50));
        }
        expect(done(), isTrue);
      }

      await until(() => library.recorded.isNotEmpty && !controller.dirty);
      expect(controller.renameDay('Renamed'), isNull);
      expect(controller.dirty, isTrue);
      service.gate!.complete();
      await until(() => controller.weather.of(id) != null);
      await tester.pump();
      expect(library.weatherRecorded, isEmpty);
      // Saved by itself after a moment; that save records the weather.
      await until(() => library.recorded.last?[id] != null);
      expect(library.weatherRecorded, isEmpty);
      await tester.pumpWidget(const SizedBox());
      await tester.pump(const Duration(seconds: 3));
    },
  );
}
