import 'dart:convert';

/// JSON exactly as Qt 6 (`QJsonDocument`) reads and writes it.
///
/// FlappedEar Overlays derives document ids from SHA-256 over
/// `QJsonDocument::toJson(QJsonDocument::Compact)`. Telemetry must produce the
/// same bytes. The rules below were taken from Qt 6.8.3 (`qjsonparser.cpp`,
/// `qjsonvalue.cpp`, `qjsonwriter.cpp`, `qlocale_tools.cpp`) and are checked
/// against vectors generated by Overlays itself.
///
/// Values are `null`, `bool`, `int`, `double`, `String`, `List<Object?>` and
/// `Map<String, Object?>`.

// 2^53: Qt stores an integral double as an integer only up to this magnitude
// (`QJsonValue(double)` refuses a precision upgrade).
const double _maxMantissa = 9007199254740992.0;

// The int64 range as doubles: [-2^63, 2^63).
const double _int64Min = -9223372036854775808.0;
const double _int64End = 9223372036854775808.0;

/// The deepest nesting [qtJsonDecode] reads when no [maxDepth] is given:
/// Qt's own parser refuses more than 1024 levels.
const int qtJsonMaximumDepth = 1024;

/// A value nested deeper than the limit [qtJsonDecode] was given.
final class QtJsonDepthException extends FormatException {
  QtJsonDepthException(this.maxDepth)
    : super('JSON nesting exceeds $maxDepth levels.');

  /// The deepest nesting that was allowed.
  final int maxDepth;
}

/// Parses [text] like `QJsonDocument::fromJson`: every integral number that
/// fits in int64 becomes an `int`, whether it was written as `1`, `1.0` or
/// `1e0`.
///
/// A value nested more than [maxDepth] levels deep (the top level is level 0)
/// throws [QtJsonDepthException] before it is walked, so a small text of
/// thousands of brackets cannot exhaust the stack.
Object? qtJsonDecode(String text, {int maxDepth = qtJsonMaximumDepth}) {
  _rejectDeepNesting(text, maxDepth);
  return _normalizeParsed(jsonDecode(text), 0, maxDepth);
}

/// Throws [QtJsonDepthException] when [text] opens more than `maxDepth + 1`
/// arrays or objects at once, reading no more than the brackets, so a text of
/// millions of them is refused before it is parsed into as many objects. A
/// value one level too deep inside a permitted count is found after parsing.
void _rejectDeepNesting(String text, int maxDepth) {
  var open = 0;
  var inString = false;
  for (var i = 0; i < text.length; i++) {
    final unit = text.codeUnitAt(i);
    if (inString) {
      if (unit == 0x5c) {
        i++;
      } else if (unit == 0x22) {
        inString = false;
      }
    } else if (unit == 0x22) {
      inString = true;
    } else if (unit == 0x5b || unit == 0x7b) {
      if (++open > maxDepth + 1) throw QtJsonDepthException(maxDepth);
    } else if (unit == 0x5d || unit == 0x7d) {
      if (open > 0) open--;
    }
  }
}

Object? _normalizeParsed(Object? value, int depth, int maxDepth) {
  if (depth > maxDepth) throw QtJsonDepthException(maxDepth);
  if (value is double) {
    if (value.isFinite &&
        value == value.truncateToDouble() &&
        value >= _int64Min &&
        value < _int64End) {
      return value.toInt();
    }
    return value;
  }
  if (value is List) {
    return [
      for (final item in value) _normalizeParsed(item, depth + 1, maxDepth),
    ];
  }
  if (value is Map) {
    return {
      for (final entry in value.entries)
        entry.key as String: _normalizeParsed(entry.value, depth + 1, maxDepth),
    };
  }
  return value;
}

/// The compact JSON text Qt writes for [value].
String qtCompactJson(Object? value) {
  final buffer = StringBuffer();
  _write(value, buffer);
  return buffer.toString();
}

/// The UTF-8 bytes of [qtCompactJson], which is what Overlays hashes.
List<int> qtCompactJsonBytes(Object? value) =>
    utf8.encode(qtCompactJson(value));

void _write(Object? value, StringBuffer out) {
  switch (value) {
    case null:
      out.write('null');
    case bool():
      out.write(value ? 'true' : 'false');
    case int():
      out.write(value);
    case double():
      out.write(qtFormatDouble(value));
    case String():
      _writeString(value, out);
    case List():
      out.write('[');
      for (var i = 0; i < value.length; i++) {
        if (i > 0) out.write(',');
        _write(value[i], out);
      }
      out.write(']');
    case Map():
      final keys = [for (final key in value.keys) key as String]
        ..sort(compareByCodePoint);
      out.write('{');
      for (var i = 0; i < keys.length; i++) {
        if (i > 0) out.write(',');
        _writeString(keys[i], out);
        out.write(':');
        _write(value[keys[i]], out);
      }
      out.write('}');
    default:
      throw ArgumentError.value(value, 'value', 'not a JSON value');
  }
}

/// Orders object keys as Qt does: by Unicode code point, so a character
/// outside the Basic Multilingual Plane sorts after U+FFFF.
int compareByCodePoint(String a, String b) {
  final left = a.runes.iterator;
  final right = b.runes.iterator;
  while (true) {
    final hasLeft = left.moveNext();
    final hasRight = right.moveNext();
    if (!hasLeft) return hasRight ? -1 : 0;
    if (!hasRight) return 1;
    final difference = left.current - right.current;
    if (difference != 0) return difference;
  }
}

const _hex = '0123456789abcdef';

void _writeString(String value, StringBuffer out) {
  out.write('"');
  final units = value.codeUnits;
  for (var i = 0; i < units.length; i++) {
    final unit = units[i];
    if (unit < 0x80) {
      switch (unit) {
        case 0x22:
          out.write(r'\"');
        case 0x5c:
          out.write(r'\\');
        case 0x08:
          out.write(r'\b');
        case 0x0c:
          out.write(r'\f');
        case 0x0a:
          out.write(r'\n');
        case 0x0d:
          out.write(r'\r');
        case 0x09:
          out.write(r'\t');
        default:
          if (unit < 0x20) {
            out.write('\\u00${_hex[unit >> 4]}${_hex[unit & 0xf]}');
          } else {
            out.writeCharCode(unit);
          }
      }
    } else if (unit >= 0xd800 &&
        unit <= 0xdbff &&
        i + 1 < units.length &&
        units[i + 1] >= 0xdc00 &&
        units[i + 1] <= 0xdfff) {
      out.writeCharCode(unit);
      out.writeCharCode(units[++i]);
    } else if (unit >= 0xd800 && unit <= 0xdfff) {
      // A lone surrogate has no UTF-8 form; Qt writes a JSON escape.
      out.write('\\u');
      for (final shift in const [12, 8, 4, 0]) {
        out.write(_hex[(unit >> shift) & 0xf]);
      }
    } else {
      out.writeCharCode(unit);
    }
  }
  out.write('"');
}

/// Formats [value] as Qt's JSON writer does.
///
/// An integral value up to 2^53 in magnitude is written as an integer, the
/// way `QJsonValue(double)` stores it. Any other finite value uses the
/// shortest round-trip digits in decimal or exponent form, whichever is
/// shorter (`QByteArray::number(d, 'g', QLocale::FloatingPointShortest)`).
/// Non-finite values are written as `null`, and negative zero as `0`.
String qtFormatDouble(double value) {
  if (!value.isFinite) return 'null';
  if (value == value.truncateToDouble() &&
      value <= _maxMantissa &&
      value >= -_maxMantissa - 1) {
    return value.toInt().toString();
  }
  // Dart's toStringAsExponential() without an argument gives the shortest
  // digits that round-trip, as in "-1.2345e+21".
  final exponential = value.toStringAsExponential();
  final negative = exponential.startsWith('-');
  final body = negative ? exponential.substring(1) : exponential;
  final e = body.indexOf('e');
  final digits = body.substring(0, e).replaceFirst('.', '');
  final decpt = int.parse(body.substring(e + 1)) + 1;
  final length = digits.length;

  var bias = 4;
  if (length <= decpt && length > 1) {
    bias++;
  } else if (length == 1 && decpt <= 0) {
    bias--;
  }
  final bool useDecimal;
  if (decpt <= 0) {
    useDecimal = 1 - decpt <= bias;
  } else if (decpt <= length) {
    useDecimal = true;
  } else {
    useDecimal = decpt <= length + bias;
  }

  final out = StringBuffer(negative ? '-' : '');
  if (useDecimal) {
    if (decpt < 0) {
      out.write('0.0');
      for (var i = decpt + 1; i < 0; i++) {
        out.write('0');
      }
      out.write(digits);
    } else if (decpt == 0) {
      out
        ..write('0.')
        ..write(digits);
    } else if (decpt >= length) {
      out
        ..write(digits)
        ..write('0' * (decpt - length));
    } else {
      out
        ..write(digits.substring(0, decpt))
        ..write('.')
        ..write(digits.substring(decpt));
    }
  } else {
    out.write(digits[0]);
    if (length > 1) {
      out
        ..write('.')
        ..write(digits.substring(1));
    }
    final exponent = decpt - 1;
    out
      ..write(exponent < 0 ? 'e-' : 'e+')
      ..write(exponent.abs().toString().padLeft(2, '0'));
  }
  return out.toString();
}
