import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:telemetry/l10n.dart';
import 'package:telemetry/day/day_results_controller.dart';
import 'package:telemetry/day/day_results_page.dart';
import 'package:telemetry/day/document_pickers.dart';
import 'package:telemetry/day/recovery_store.dart';
import 'package:telemetry/import/day_import_controller.dart';
import 'package:telemetry/import/day_import_page.dart';
import 'package:telemetry/import/import_runner.dart';
import 'package:telemetry/import/incoming_recordings.dart';
import 'package:telemetry/main.dart';
import 'package:telemetry/ui/theme.dart';
import 'package:telemetry_core/telemetry_core.dart';

import '../day/day_results_page_test.dart' show circuitVbo;
import '../day/recovery_test.dart' show FileRecoveryStore;
import '../support/temp_directory.dart';

/// A job the test finishes by hand.
final class _FakeJob implements DayImportJob {
  _FakeJob(this.request, this.progress, [this.choices]);
  final DayImportRequest request;
  final ImportChoices? choices;
  final void Function(int, int) progress;
  final completer = Completer<DayImportOutcome>();
  bool cancelled = false;

  @override
  Future<DayImportOutcome> get result => completer.future;

  @override
  void cancel() {
    cancelled = true;
    if (!completer.isCompleted) {
      completer.completeError(const OperationCancelled());
    }
  }

  /// Runs the real scan and plan synchronously and delivers the result.
  void finish() => completer.complete(runDayImport(request, choices: choices));
}

final class _FakeImporter implements DayImporter {
  final jobs = <_FakeJob>[];

  @override
  DayImportJob start(
    DayImportRequest request,
    void Function(int, int) progress, {
    ImportChoices? choices,
  }) {
    final job = _FakeJob(request, progress, choices);
    jobs.add(job);
    return job;
  }
}

/// Prepares additions to a day on the test's own thread.
final class _SyncAppender implements DayAppender {
  @override
  DayAppendJob start(DayAppendRequest request, void Function(int, int) _) =>
      _SyncAppendJob(runDayAppend(request));
}

final class _SyncAppendJob implements DayAppendJob {
  _SyncAppendJob(DayAppendOutcome outcome) : result = Future.value(outcome);

  @override
  final Future<DayAppendOutcome> result;

  @override
  void cancel() {}
}

final class _FakeIncoming implements IncomingRecordings {
  final controller = StreamController<List<String>>.broadcast();

  @override
  Stream<List<String>> get received => controller.stream;
}

final class _FakePickers implements RecordingPickers {
  List<String> recordings = const [];
  String? folder;

  @override
  Future<List<String>> pickRecordings() async => recordings;

  @override
  Future<String?> pickFolder() async => folder;
}

/// A dated RaceChrono export without a start/finish line, starting at
/// [hour]:00 UTC on 2 October 2026.
String _datedVbo({required int hour, int speed = 72, int day = 2}) {
  final clock = hour.toString().padLeft(2, '0');
  final date = day.toString().padLeft(2, '0');
  final rows = StringBuffer();
  for (var i = 0; i < 5; ++i) {
    rows.write('${clock}000$i.000 3000.000000 -1200.000000 $speed\n');
  }
  return 'File created on $date/10/2026 at $clock:00:00\n'
      '[comments]\nGenerated by RaceChrono Pro v10.2.4\n'
      '[column names]\ntime latitude longitude velocity\n[data]\n$rows';
}

/// An undated recording with three laps through its start/finish line.
const String _lapsVbo =
    '[header]\ncoordinate units = degrees\n'
    '[laptiming]\nStart 21.0000 52.0000 21.0000 52.0002 start\n'
    '[column names]\ntime latitude longitude\n[data]\n'
    '0 52.0001 21.0002\n1 52.0001 21.0002\n2 52.0001 20.9998\n'
    '3 52.0008 20.9998\n4 52.0008 21.0002\n5 52.0001 21.0002\n'
    '6 52.0001 20.9998\n7 52.0008 20.9998\n8 52.0008 21.0002\n'
    '10 52.0001 21.0002\n11 52.0001 20.9998\n12 52.0008 20.9998\n'
    '13 52.0008 21.0002\n14 52.0001 21.0002\n15 52.0001 20.9998\n';

/// Runs real time until every queued recovery write or clear has finished.
///
/// A write still running when a test ends holds its file open, so the temp
/// folder cannot be deleted on Windows. Its rest then never runs, because it
/// belongs to the finished test's fake clock, and the next test's recovery
/// work waits behind it until the test times out.
Future<void> settleRecovery(WidgetTester tester) async {
  for (var i = 0; i < 500 && !recoveryQueueIdle; ++i) {
    await tester.runAsync(
      () => Future<void>.delayed(const Duration(milliseconds: 20)),
    );
    await tester.pump();
  }
  expect(recoveryQueueIdle, isTrue, reason: 'recovery work still running');
}

void main() {
  late Directory directory;
  late _FakeImporter importer;
  late _FakePickers pickers;
  late DayImportController controller;
  late FileRecoveryStore recovery;

  setUp(() {
    // An earlier test left recovery work running: fail here, not in a
    // ten-minute timeout.
    expect(recoveryQueueIdle, isTrue, reason: 'recovery work left running');
    directory = Directory.systemTemp.createTempSync('day_import_page');
    importer = _FakeImporter();
    pickers = _FakePickers();
    controller = DayImportController(importer: importer);
    recovery = FileRecoveryStore('${directory.path}/recovery.json');
  });
  tearDown(() {
    controller.dispose();
    deleteTemporaryDirectory(directory);
  });

  String write(String name, String text) {
    final path = '${directory.path}/$name';
    File(path).writeAsStringSync(text, flush: true);
    return path;
  }

  /// Desktop choices by default; [picksFolders] null follows the platform.
  /// No day is kept or saved yet.
  Future<void> show(
    WidgetTester tester, {
    bool? picksFolders = true,
    Locale? locale,
  }) async {
    await tester.pumpWidget(
      TelemetryApp(
        locale: locale,
        home: DayImportPage(
          controller: controller,
          pickers: pickers,
          picksFolders: picksFolders,
          recovery: recovery,
          documents: _SavedDays(const []),
          appender: _SyncAppender(),
        ),
      ),
    );
    // The places appear once the start page has been built.
    await tester.pump();
  }

  /// Lets file and isolate work run between frames until [done].
  Future<void> pumpUntil(WidgetTester tester, bool Function() done) async {
    for (var i = 0; i < 200 && !done(); ++i) {
      await tester.runAsync(
        () => Future<void>.delayed(const Duration(milliseconds: 20)),
      );
      await tester.pump();
    }
    expect(done(), isTrue);
  }

  /// Taps [button] and waits for the import it starts: with no day of
  /// today to continue, the picked recordings are imported as a new day.
  Future<void> pick(
    WidgetTester tester, {
    String button = 'Import sessions…',
  }) async {
    final before = importer.jobs.length;
    await tester.tap(find.text(button));
    await pumpUntil(tester, () => importer.jobs.length > before);
    await tester.pump();
  }

  /// Finishes the import, whose day opens by itself, and goes back to the
  /// import page, which then lists the day's sessions.
  Future<void> finishAndGoBack(WidgetTester tester) async {
    importer.jobs.last.finish();
    await tester.pumpAndSettle();
    expect(find.byType(DayResultsPage), findsOneWidget);
    Navigator.of(tester.element(find.byType(DayResultsPage))).pop();
    await tester.pumpAndSettle();
    await pumpUntil(
      tester,
      () => find.byKey(const ValueKey('lastDay')).evaluate().isNotEmpty,
    );
  }

  testWidgets(
    'phones and tablets offer recordings only, not a folder',
    (tester) async {
      final vbo = write('a.vbo', _datedVbo(hour: 9));
      pickers.recordings = [vbo];
      await show(tester, picksFolders: null);

      expect(
        find.textContaining('Choose the VBO or RCZ recording of each session'),
        findsOneWidget,
      );
      expect(find.text('Choose a folder…'), findsNothing);
      expect(find.text('Include subfolders'), findsNothing);
      // Sessions are imported one by one; the app makes the day.
      expect(find.text('Import sessions…'), findsOneWidget);
      expect(find.text('Review the files before importing'), findsNothing);

      await pick(tester);
      expect(controller.isWorking, isTrue);
      // The day opens by itself, with its Save button.
      importer.jobs.single.finish();
      await tester.pumpAndSettle();
      expect(find.text('Day results'), findsOneWidget);
      expect(find.byTooltip('Save'), findsOneWidget);
      await tester.pumpWidget(const SizedBox());
      await settleRecovery(tester);
    },
    variant: const TargetPlatformVariant({
      TargetPlatform.iOS,
      TargetPlatform.android,
    }),
  );

  testWidgets(
    'desktops offer a folder too',
    (tester) async {
      await show(tester, picksFolders: null);
      expect(find.text('Choose a folder…'), findsOneWidget);
    },
    variant: const TargetPlatformVariant({
      TargetPlatform.macOS,
      TargetPlatform.windows,
    }),
  );

  testWidgets('recordings shared from another app are imported', (
    tester,
  ) async {
    final incoming = _FakeIncoming();
    final vbo = write('shared.vbo', _datedVbo(hour: 9));
    await tester.pumpWidget(
      TelemetryApp(
        home: DayImportPage(
          controller: controller,
          pickers: pickers,
          incoming: incoming,
        ),
      ),
    );

    incoming.controller.add([vbo]);
    await tester.pump();
    await tester.pump();
    expect(importer.jobs.single.request.paths, [vbo]);
    importer.jobs.single.finish();
    await tester.pumpAndSettle();
    // With no day of today to continue, the shared recording's day opens
    // by itself.
    expect(find.text('Day results'), findsOneWidget);
    Navigator.of(tester.element(find.text('Day results'))).pop();
    await tester.pumpAndSettle();
    // The day was handed over: it is not built afresh from the import,
    // which would leave out what was added to it.
    expect(find.text('1 session imported'), findsNothing);

    // Leaving the page stops listening.
    await tester.pumpWidget(const SizedBox());
    expect(incoming.controller.hasListener, isFalse);
    await settleRecovery(tester);
  });

  testWidgets('a recording shared during that import goes to its day', (
    tester,
  ) async {
    final incoming = _FakeIncoming();
    await tester.binding.setSurfaceSize(const Size(400, 3000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await tester.pumpWidget(
      TelemetryApp(
        home: DayImportPage(
          controller: controller,
          pickers: pickers,
          incoming: incoming,
          appender: _SyncAppender(),
        ),
      ),
    );
    final first = write('first.vbo', _datedVbo(hour: 9));
    incoming.controller.add([first]);
    await tester.pump();
    await tester.pump();
    expect(importer.jobs.single.request.paths, [first]);
    // The next session is shared while the first one is still imported.
    incoming.controller.add([write('second.vbo', _datedVbo(hour: 11))]);
    await tester.pump();
    expect(importer.jobs, hasLength(1));
    expect(find.textContaining('Nothing was imported'), findsNothing);
    importer.jobs.single.finish();
    for (var i = 0; i < 20; ++i) {
      await tester.runAsync(
        () => Future<void>.delayed(const Duration(milliseconds: 20)),
      );
      await tester.pump();
    }
    await tester.pumpAndSettle();
    expect(find.text('Day results'), findsOneWidget);
    expect(find.text('Session 2 added to the day.'), findsOneWidget);
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('sessions picked one by one make one day, listed here', (
    tester,
  ) async {
    await tester.binding.setSurfaceSize(const Size(400, 3000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    pickers.recordings = [write('a.vbo', _datedVbo(hour: 9))];
    await show(tester, picksFolders: false);
    await pick(tester);
    await finishAndGoBack(tester);
    // Back from the day, its sessions are still here, with a way back in.
    final card = find.byKey(const ValueKey('lastDay'));
    expect(
      find.descendant(of: card, matching: find.textContaining('Not saved yet')),
      findsOneWidget,
    );
    expect(
      find.byKey(const ValueKey('importSession Session 1')),
      findsOneWidget,
    );

    // The next session is added to that day, not imported instead of it.
    pickers.recordings = [write('b.vbo', _datedVbo(hour: 11, speed: 80))];
    await tester.tap(find.text('Import sessions…'));
    await pumpUntil(
      tester,
      () => find.text('Session 2 added to the day.').evaluate().isNotEmpty,
    );
    expect(importer.jobs, hasLength(1));
    expect(find.text('Day results'), findsOneWidget);
    Navigator.of(tester.element(find.byType(DayResultsPage))).pop();
    await tester.pumpAndSettle();
    await pumpUntil(
      tester,
      () => find
          .byKey(const ValueKey('importSession Session 2'))
          .evaluate()
          .isNotEmpty,
    );
    expect(
      find.byKey(const ValueKey('importSession Session 1')),
      findsOneWidget,
    );

    // Opened again from here, with both sessions.
    await tester.tap(find.byKey(const ValueKey('openLastDay')));
    await pumpUntil(
      tester,
      () => find.byType(DayResultsPage).evaluate().isNotEmpty,
    );
    await tester.pumpAndSettle();
    expect(find.text('Day results'), findsOneWidget);
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('Home, Library and Day are on every page, and Day shows the '
      'day left at once', (tester) async {
    await tester.binding.setSurfaceSize(const Size(400, 3000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    pickers.recordings = [write('a.vbo', _datedVbo(hour: 9))];
    await show(tester, picksFolders: false);
    // The start page: the logo beside the app's name, and no day yet.
    expect(find.byKey(const ValueKey('appLogo')), findsOneWidget);
    expect(find.text('FlappedEar Telemetry'), findsOneWidget);
    expect(find.byKey(const ValueKey('appPlaces')), findsOneWidget);
    final day = find.byKey(const ValueKey('place-day'));
    expect(
      tester
          .widget<NavigationBar>(find.byKey(const ValueKey('appPlaces')))
          .destinations
          .last,
      isA<NavigationDestination>().having((d) => d.enabled, 'enabled', false),
    );

    await pick(tester);
    importer.jobs.single.finish();
    await tester.pumpAndSettle();
    expect(find.text('Day results'), findsOneWidget);
    // The day page has the same places, Day chosen, and its own tabs.
    expect(find.byKey(const ValueKey('appPlaces')), findsOneWidget);
    expect(find.byKey(const ValueKey('daySection-laps')), findsOneWidget);
    final shown = tester
        .widget<NavigationBar>(find.byKey(const ValueKey('appPlaces')))
        .selectedIndex;
    expect(shown, 1);

    await tester.tap(find.byKey(const ValueKey('place-home')));
    await tester.pumpAndSettle();
    await pumpUntil(
      tester,
      () => find.byKey(const ValueKey('lastDay')).evaluate().isNotEmpty,
    );
    expect(find.byType(DayResultsPage), findsNothing);

    // Back to the same day, without opening it again.
    await tester.tap(day);
    await tester.pumpAndSettle();
    expect(find.text('Day results'), findsOneWidget);
    expect(importer.jobs, hasLength(1));
    // Its laps tab, then Home and back: the day is still the one shown.
    await tester.tap(find.byKey(const ValueKey('daySection-laps')));
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('dayResultsLaps')), findsOneWidget);
    await tester.tap(find.byKey(const ValueKey('place-home')));
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const ValueKey('openLastDay')));
    await tester.pumpAndSettle();
    expect(find.text('Day results'), findsOneWidget);
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('Coach shows the day open now on its coach', (tester) async {
    await tester.binding.setSurfaceSize(const Size(400, 3000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    pickers.recordings = [write('a.vbo', _datedVbo(hour: 9))];
    await show(tester, picksFolders: false);
    final coach = find.byKey(const ValueKey('place-coach'));
    int selected() => tester
        .widget<NavigationBar>(find.byKey(const ValueKey('appPlaces')))
        .selectedIndex;
    // Greyed out until a day is open.
    expect(
      tester
          .widget<NavigationBar>(find.byKey(const ValueKey('appPlaces')))
          .destinations
          .last,
      isA<NavigationDestination>().having((d) => d.enabled, 'enabled', false),
    );
    await pick(tester);
    importer.jobs.single.finish();
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('dayResultsCoach')), findsNothing);

    // From the day's tabs to its coach, and back with a tab.
    await tester.tap(coach);
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('dayResultsCoach')), findsOneWidget);
    expect(find.byKey(const ValueKey('dayResultsSummary')), findsNothing);
    expect(selected(), 2);
    await tester.tap(find.byKey(const ValueKey('daySection-overview')));
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('dayResultsCoach')), findsNothing);
    expect(selected(), 1);

    // From Home straight to the coach of the day left, without opening it
    // again; Day then shows its tabs.
    await tester.tap(find.byKey(const ValueKey('place-home')));
    await tester.pumpAndSettle();
    expect(find.byType(DayResultsPage), findsNothing);
    await tester.tap(coach);
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('dayResultsCoach')), findsOneWidget);
    expect(importer.jobs, hasLength(1));
    expect(selected(), 2);
    await tester.tap(find.byKey(const ValueKey('place-day')));
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('dayResultsCoach')), findsNothing);
    expect(find.byKey(const ValueKey('dayResultsSummary')), findsOneWidget);
    expect(selected(), 1);

    // Left on its coach, the day opened again from Home shows its tabs.
    await tester.tap(coach);
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const ValueKey('place-home')));
    await tester.pumpAndSettle();
    await pumpUntil(
      tester,
      () => find.byKey(const ValueKey('openLastDay')).evaluate().isNotEmpty,
    );
    await tester.tap(find.byKey(const ValueKey('openLastDay')));
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('dayResultsCoach')), findsNothing);
    expect(find.byKey(const ValueKey('dayResultsSummary')), findsOneWidget);
    expect(selected(), 1);
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('Day tapped while the day is still leaving keeps it working', (
    tester,
  ) async {
    await tester.binding.setSurfaceSize(const Size(400, 3000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    pickers.recordings = [write('a.vbo', _datedVbo(hour: 9))];
    await show(tester, picksFolders: false);
    await pick(tester);
    importer.jobs.single.finish();
    await tester.pumpAndSettle();
    // Back to Day before the day page has finished closing.
    await tester.tap(find.byKey(const ValueKey('place-home')));
    await tester.pump(const Duration(milliseconds: 50));
    await tester.tap(find.byKey(const ValueKey('place-day')));
    await tester.pumpAndSettle();
    expect(find.text('Day results'), findsOneWidget);
    // Still the live day: the next session is added to it and said.
    pickers.recordings = [write('b.vbo', _datedVbo(hour: 11, speed: 80))];
    await tester.tap(find.byKey(const ValueKey('place-home')));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Import sessions…'));
    await pumpUntil(
      tester,
      () => find.text('Session 2 added to the day.').evaluate().isNotEmpty,
    );
    expect(importer.jobs, hasLength(1));
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('the places do nothing while a dialog is open', (tester) async {
    await tester.binding.setSurfaceSize(const Size(400, 3000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    pickers.recordings = [write('a.vbo', _datedVbo(hour: 9))];
    await show(tester, picksFolders: false);
    await pick(tester);
    importer.jobs.single.finish();
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const ValueKey('place-home')));
    await tester.pumpAndSettle();
    await tester.tap(find.byTooltip('Settings'));
    await tester.pumpAndSettle();
    expect(find.byType(Dialog), findsOneWidget);
    await tester.tap(find.byKey(const ValueKey('place-day')));
    await tester.pumpAndSettle();
    expect(find.byType(Dialog), findsOneWidget);
    expect(find.byType(DayResultsPage), findsNothing);
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('a wide window has the places in a side rail', (tester) async {
    await tester.binding.setSurfaceSize(const Size(1280, 800));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    pickers.recordings = [write('a.vbo', _datedVbo(hour: 9))];
    await show(tester, picksFolders: false);
    NavigationRail rail() =>
        tester.widget<NavigationRail>(find.byKey(const ValueKey('appPlaces')));
    // Day and Coach are greyed out until a day is open.
    expect(rail().destinations.skip(1).map((d) => d.disabled), [true, true]);
    await pick(tester);
    importer.jobs.single.finish();
    await tester.pumpAndSettle();
    expect(rail().selectedIndex, 1);
    await tester.tap(find.byKey(const ValueKey('place-coach')));
    await tester.pumpAndSettle();
    expect(find.byKey(const ValueKey('dayResultsCoach')), findsOneWidget);
    expect(rail().selectedIndex, 2);
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('a saved day closed here takes the next session', (tester) async {
    await tester.binding.setSurfaceSize(const Size(400, 3000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    final saved = '${directory.path}/Today.fetproject';
    pickers.recordings = [write('a.vbo', _datedVbo(hour: 9))];
    // Saved anywhere, as on a desktop, where the app lists no saved days.
    await tester.pumpWidget(
      TelemetryApp(
        home: DayImportPage(
          controller: controller,
          pickers: pickers,
          picksFolders: false,
          recovery: recovery,
          documents: _SavedDays(const [], saveTo: saved),
          appender: _SyncAppender(),
        ),
      ),
    );
    await pick(tester);
    importer.jobs.single.finish();
    await tester.pumpAndSettle();
    // The day's background analysis finishes first, so the save keeps all.
    for (var i = 0; i < 50; ++i) {
      await tester.runAsync(
        () => Future<void>.delayed(const Duration(milliseconds: 20)),
      );
      await tester.pump();
    }
    await tester.tap(find.byTooltip('Save'));
    // Saved once the day takes its file's name.
    await pumpUntil(tester, () => find.text('Day results').evaluate().isEmpty);
    await tester.pumpAndSettle();
    final page = find.byType(DayResultsPage);
    Navigator.of(tester.element(page)).pop();
    await tester.pumpAndSettle();
    await pumpUntil(
      tester,
      () => find
          .descendant(
            of: find.byKey(const ValueKey('lastDay')),
            matching: find.text('Saved as Today.fetproject.'),
          )
          .evaluate()
          .isNotEmpty,
    );

    pickers.recordings = [write('b.vbo', _datedVbo(hour: 11, speed: 80))];
    await tester.tap(find.text('Import sessions…'));
    await pumpUntil(
      tester,
      () => find.byType(DayResultsPage).evaluate().isNotEmpty,
    );
    await tester.pumpAndSettle();
    expect(find.textContaining('Session 2 added to the day.'), findsOneWidget);
    expect(importer.jobs, hasLength(1));
    // Added and saved again in its file.
    final runs = (readDayDocument(saved)['event'] as Map)['runs'] as List;
    expect(runs, hasLength(2));
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('a share while a day is open imports behind it and says so', (
    tester,
  ) async {
    final incoming = _FakeIncoming();
    final vbo = write('shared.vbo', _datedVbo(hour: 9));
    await tester.pumpWidget(
      TelemetryApp(
        home: DayImportPage(
          controller: controller,
          pickers: pickers,
          incoming: incoming,
        ),
      ),
    );
    final navigator = tester.state<NavigatorState>(find.byType(Navigator));
    navigator.push(
      MaterialPageRoute<void>(
        builder: (_) => const Scaffold(body: Text('An open day')),
      ),
    );
    await tester.pumpAndSettle();

    incoming.controller.add([vbo]);
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 500));
    expect(importer.jobs.single.request.paths, [vbo]);
    expect(find.text('An open day'), findsOneWidget);
    expect(
      find.text(
        'Importing the shared recordings. Go back to Import sessions to see '
        'them.',
      ),
      findsOneWidget,
    );
  });

  testWidgets('a share while a day is shown adds it to that day', (
    tester,
  ) async {
    final incoming = _FakeIncoming();
    pickers.recordings = [write('a.vbo', _datedVbo(hour: 9))];
    final shared = write('shared.vbo', _datedVbo(hour: 11, speed: 80));
    await tester.binding.setSurfaceSize(const Size(400, 3000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await tester.pumpWidget(
      TelemetryApp(
        home: DayImportPage(
          controller: controller,
          pickers: pickers,
          incoming: incoming,
          appender: _SyncAppender(),
          recovery: recovery,
          documents: _SavedDays(const []),
        ),
      ),
    );
    await pick(tester);
    importer.jobs.single.finish();
    await tester.pumpAndSettle();

    await tester.runAsync(() async {
      incoming.controller.add([shared]);
      await Future<void>.delayed(const Duration(milliseconds: 50));
    });
    await tester.pumpAndSettle();
    // No second import: the day itself took the recording.
    expect(importer.jobs, hasLength(1));
    expect(find.text('Session 2 added to the day.'), findsOneWidget);
    expect(find.text('Day results'), findsOneWidget);
    // The day moves to its coach, and the bar with it.
    expect(find.byKey(const ValueKey('dayResultsCoach')), findsOneWidget);
    expect(
      tester
          .widget<NavigationBar>(find.byKey(const ValueKey('appPlaces')))
          .selectedIndex,
      2,
    );
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  group('a share with no day shown', () {
    late FileRecoveryStore store;
    setUp(
      () => store = FileRecoveryStore('${directory.path}/day-recovery.json'),
    );

    /// Keeps an unsaved day of [path] for recovery, as the app does while
    /// a day is open.
    Future<void> keepUnsaved(String path) async {
      final outcome = runDayImport((paths: [path], includeSubfolders: false));
      final day = DayResultsController(
        runs: outcome.runs,
        analysis: outcome.analysis!,
        recovery: store,
      );
      await day.flushRecovery();
      day.dispose();
    }

    /// Lets background isolates run while the page's own work, which runs
    /// in the test's clock, moves on, until [done].
    Future<void> pumpUntil(WidgetTester tester, bool Function() done) async {
      for (var i = 0; i < 200 && !done(); ++i) {
        await tester.runAsync(
          () => Future<void>.delayed(const Duration(milliseconds: 20)),
        );
        await tester.pump();
      }
      expect(done(), isTrue);
    }

    Future<void> showWith(WidgetTester tester, _FakeIncoming incoming) async {
      await tester.binding.setSurfaceSize(const Size(400, 3000));
      addTearDown(() => tester.binding.setSurfaceSize(null));
      await tester.pumpWidget(
        TelemetryApp(
          home: DayImportPage(
            controller: controller,
            pickers: pickers,
            incoming: incoming,
            recovery: store,
            appender: _SyncAppender(),
          ),
        ),
      );
    }

    testWidgets('continues today\'s unsaved day', (tester) async {
      final incoming = _FakeIncoming();
      await tester.runAsync(
        () => keepUnsaved(write('a.vbo', _datedVbo(hour: 10))),
      );
      await showWith(tester, incoming);
      final shared = write('b.vbo', _datedVbo(hour: 12, speed: 80));
      incoming.controller.add([shared]);
      await pumpUntil(
        tester,
        () => find.text('Day results').evaluate().isNotEmpty,
      );
      await tester.pumpAndSettle();
      expect(importer.jobs, isEmpty);
      expect(find.text('Day results'), findsOneWidget);
      expect(find.text('Session 2 added to the day.'), findsOneWidget);

      // Closing the day writes its recovery file; let that finish here, not
      // in the next test (see [settleRecovery]).
      await tester.pumpWidget(const SizedBox());
      await settleRecovery(tester);
    });

    testWidgets('a share while a day is being restored goes to that day', (
      tester,
    ) async {
      final incoming = _FakeIncoming();
      await tester.runAsync(
        () => keepUnsaved(write('a.vbo', _datedVbo(hour: 10))),
      );
      await showWith(tester, incoming);
      await pumpUntil(tester, () => find.text('Restore').evaluate().isNotEmpty);
      await tester.tap(find.text('Restore'));
      // Shared before the restored day could open.
      incoming.controller.add([write('b.vbo', _datedVbo(hour: 12, speed: 80))]);
      await pumpUntil(
        tester,
        () => find.text('Session 2 added to the day.').evaluate().isNotEmpty,
      );
      expect(importer.jobs, isEmpty);
      expect(find.text('Day results'), findsOneWidget);

      await tester.pumpWidget(const SizedBox());
      await settleRecovery(tester);
    });

    testWidgets('another day\'s unsaved work is not replaced by today\'s', (
      tester,
    ) async {
      final incoming = _FakeIncoming();
      // Today's day, saved in the app.
      final saved = '${directory.path}/Today.fetproject';
      await tester.runAsync(() async {
        final outcome = runDayImport((
          paths: [write('a.vbo', _datedVbo(hour: 10))],
          includeSubfolders: false,
        ));
        final day = DayResultsController(
          runs: outcome.runs,
          analysis: outcome.analysis!,
        );
        await day.save(saved);
        day.dispose();
        // Then an older day changed and left unsaved.
        await keepUnsaved(write('x.vbo', _datedVbo(hour: 9, day: 5)));
      });
      final before = await tester.runAsync(store.load);
      await tester.binding.setSurfaceSize(const Size(400, 3000));
      addTearDown(() => tester.binding.setSurfaceSize(null));
      await tester.pumpWidget(
        TelemetryApp(
          home: DayImportPage(
            controller: controller,
            pickers: pickers,
            incoming: incoming,
            recovery: store,
            appender: _SyncAppender(),
            documents: _SavedDays([saved]),
          ),
        ),
      );
      final shared = write('b.vbo', _datedVbo(hour: 12, speed: 80));
      incoming.controller.add([shared]);
      await pumpUntil(tester, () => importer.jobs.isNotEmpty);
      // Imported here, next to the offer to restore the other day.
      expect(importer.jobs.single.request.paths, [shared]);
      for (var i = 0; i < 10; ++i) {
        await tester.runAsync(
          () => Future<void>.delayed(const Duration(milliseconds: 20)),
        );
        await tester.pump();
      }
      final after = await tester.runAsync(store.load);
      expect(after!.timestamp, before!.timestamp);
      expect(
        (after.document['event'] as Map)['id'],
        (before.document['event'] as Map)['id'],
      );
      final runs = (readDayDocument(saved)['event'] as Map)['runs'] as List;
      expect(runs, hasLength(1));

      // The next share is imported with the first, as one day.
      importer.jobs.single.finish();
      await tester.pump();
      final next = write('c.vbo', _datedVbo(hour: 14, speed: 75));
      incoming.controller.add([next]);
      await pumpUntil(tester, () => importer.jobs.length == 2);
      expect(importer.jobs.last.request.paths, [shared, next]);
    });

    /// The import page with [store] and desktop choices; [open] is the day
    /// "Open a saved day…" picks.
    Future<void> showDesktop(WidgetTester tester, {String? open}) async {
      await tester.binding.setSurfaceSize(const Size(800, 3000));
      addTearDown(() => tester.binding.setSurfaceSize(null));
      await tester.pumpWidget(
        TelemetryApp(
          home: DayImportPage(
            controller: controller,
            pickers: pickers,
            picksFolders: true,
            recovery: store,
            appender: _SyncAppender(),
            documents: _SavedDays(const [], open: open),
          ),
        ),
      );
    }

    testWidgets('a folder does not replace another day\'s unsaved work', (
      tester,
    ) async {
      await tester.runAsync(
        () => keepUnsaved(write('a.vbo', _datedVbo(hour: 10))),
      );
      final before = await tester.runAsync(store.load);
      Directory('${directory.path}/day').createSync();
      write('day/run.vbo', _datedVbo(hour: 9, day: 5));
      pickers.folder = '${directory.path}/day';
      await showDesktop(tester);
      await tester.tap(find.text('Choose a folder…'));
      await pumpUntil(tester, () => importer.jobs.isNotEmpty);
      importer.jobs.single.finish();
      await tester.pumpAndSettle();
      // Imported, but not opened: it stays here to be opened by hand.
      expect(find.byType(DayResultsPage), findsNothing);
      expect(find.text('1 session imported'), findsOneWidget);
      expect(find.text('Open the day'), findsOneWidget);
      final after = await tester.runAsync(store.load);
      expect(after!.eventId, before!.eventId);
      expect(after.timestamp, before.timestamp);
    });

    testWidgets('a picked recording of another date leaves unsaved work', (
      tester,
    ) async {
      await tester.runAsync(
        () => keepUnsaved(write('a.vbo', _datedVbo(hour: 10))),
      );
      final before = await tester.runAsync(store.load);
      pickers.recordings = [write('b.vbo', _datedVbo(hour: 12, day: 5))];
      await showDesktop(tester);
      await tester.tap(find.text('Import sessions…'));
      await pumpUntil(tester, () => importer.jobs.isNotEmpty);
      importer.jobs.single.finish();
      await tester.pumpAndSettle();
      expect(find.byType(DayResultsPage), findsNothing);
      expect(find.text('1 session imported'), findsOneWidget);
      final after = await tester.runAsync(store.load);
      expect(after!.eventId, before!.eventId);
      expect(after.timestamp, before.timestamp);
    });

    testWidgets('another day\'s unsaved work keeps the saved day just left '
        'from opening by itself', (tester) async {
      // A saved day of 2 October, and unsaved work on another day.
      final saved = '${directory.path}/Saved.fetproject';
      await tester.runAsync(() async {
        final outcome = runDayImport((
          paths: [write('a.vbo', _datedVbo(hour: 10))],
          includeSubfolders: false,
        ));
        final day = DayResultsController(
          runs: outcome.runs,
          analysis: outcome.analysis!,
        );
        await day.save(saved);
        day.dispose();
        await keepUnsaved(write('x.vbo', _datedVbo(hour: 9, day: 5)));
      });
      final before = await tester.runAsync(store.load);
      await showDesktop(tester, open: saved);
      await tester.tap(find.text('Open a saved day…'));
      await pumpUntil(
        tester,
        () => find.byType(DayResultsPage).evaluate().isNotEmpty,
      );
      await tester.pumpAndSettle();
      Navigator.of(tester.element(find.byType(DayResultsPage))).pop();
      await tester.pumpAndSettle();
      await pumpUntil(
        tester,
        () => find
            .descendant(
              of: find.byKey(const ValueKey('lastDay')),
              matching: find.text('Saved as Saved.fetproject.'),
            )
            .evaluate()
            .isNotEmpty,
      );

      pickers.recordings = [write('b.vbo', _datedVbo(hour: 12, speed: 80))];
      await tester.tap(find.text('Import sessions…'));
      await pumpUntil(tester, () => importer.jobs.isNotEmpty);
      importer.jobs.single.finish();
      await tester.pumpAndSettle();
      // Opening a day here would let its changes replace that work: the
      // session is imported and waits to be opened by hand.
      expect(find.byType(DayResultsPage), findsNothing);
      expect(find.text('1 session imported'), findsOneWidget);
      final runs = (readDayDocument(saved)['event'] as Map)['runs'] as List;
      expect(runs, hasLength(1));
      final after = await tester.runAsync(store.load);
      expect(after!.eventId, before!.eventId);
      expect(after.timestamp, before.timestamp);
      await tester.pumpWidget(const SizedBox());
      await settleRecovery(tester);
    });

    testWidgets('a recording of another date starts its own day', (
      tester,
    ) async {
      final incoming = _FakeIncoming();
      await tester.runAsync(
        () => keepUnsaved(write('a.vbo', _datedVbo(hour: 10))),
      );
      await showWith(tester, incoming);
      final shared = write('b.vbo', _datedVbo(hour: 12, day: 5));
      incoming.controller.add([shared]);
      await pumpUntil(tester, () => importer.jobs.isNotEmpty);
      expect(importer.jobs.single.request.paths, [shared]);
    });
  });

  test('iOS picks by type identifier, desktops by extension', () {
    // file_selector on iOS refuses a group without type identifiers.
    final ios = recordingTypeGroup(TargetPlatform.iOS);
    expect(ios.uniformTypeIdentifiers, isNotEmpty);
    for (final platform in [TargetPlatform.macOS, TargetPlatform.windows]) {
      final group = recordingTypeGroup(platform);
      expect(group.extensions, containsAll(['vbo', 'rcz']));
      expect(group.uniformTypeIdentifiers, isNull);
    }
  });

  testWidgets('the pickers follow the device language', (tester) async {
    addTearDown(tester.platformDispatcher.clearLocalesTestValue);
    tester.platformDispatcher.localesTestValue = const [Locale('pl', 'PL')];
    expect(deviceL10n().importPageRecordingTypes, 'Pliki telemetrii VBO i RCZ');
    tester.platformDispatcher.localesTestValue = const [Locale('de')];
    expect(deviceL10n().importPageRecordingTypes, 'VBO and RCZ recordings');
    expect(recordingTypeGroup(TargetPlatform.macOS, label: 'X').label, 'X');
  });

  test('Android picks with the host picker, keeping file names', () async {
    // file_selector would hand back "session.bin" for a picked "session.vbo".
    debugDefaultTargetPlatformOverride = TargetPlatform.android;
    addTearDown(() => debugDefaultTargetPlatformOverride = null);
    final messenger =
        TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger;
    final calls = <String>[];
    Object? picked = ['/data/picked/1/session.vbo', '/data/picked/2/day.rcz'];
    messenger.setMockMethodCallHandler(androidPickerChannel, (call) async {
      calls.add(call.method);
      return picked;
    });
    addTearDown(
      () => messenger.setMockMethodCallHandler(androidPickerChannel, null),
    );

    const pickers = PlatformRecordingPickers();
    expect(await pickers.pickRecordings(), [
      '/data/picked/1/session.vbo',
      '/data/picked/2/day.rcz',
    ]);
    picked = null;
    expect(await pickers.pickRecordings(), isEmpty);
    expect(calls, ['pick', 'pick']);
  });

  testWidgets('a recording without GPS says GPS is missing', (tester) async {
    pickers.recordings = [
      write(
        'no-gps.vbo',
        '[column names]\ntime velocity\n[data]\n0 10\n1 11\n2 12\n',
      ),
    ];
    await show(tester);
    await pick(tester);
    await finishAndGoBack(tester);
    expect(
      find.text('No laps: the recording has no usable GPS.'),
      findsOneWidget,
    );
    expect(
      find.text('No laps: the recording has no start/finish line.'),
      findsNothing,
    );
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('imports picked recordings as sessions in recording order', (
    tester,
  ) async {
    await tester.binding.setSurfaceSize(const Size(800, 1200));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    final late = write('b-late.vbo', _datedVbo(hour: 11));
    final early = write('a-early.vbo', _datedVbo(hour: 9, speed: 80));
    final copy = write('copy.vbo', _datedVbo(hour: 9, speed: 80));
    final other = write('notes.txt', 'not a recording');
    pickers.recordings = [late, early, copy, other];
    await show(tester);

    await pick(tester);
    expect(find.text('Looking for recordings…'), findsOneWidget);
    expect(find.text('Cancel'), findsOneWidget);
    final job = importer.jobs.single;
    expect(job.request.includeSubfolders, isFalse);

    job.progress(1, 3);
    await tester.pump();
    expect(find.text('Preparing recording 2 of 3…'), findsOneWidget);

    job.finish();
    await tester.pumpAndSettle();
    // The day opens and says what was skipped.
    expect(find.text('Day results'), findsOneWidget);
    final notes = find.byKey(const ValueKey('importNotes'));
    expect(
      find.descendant(
        of: notes,
        matching: find.textContaining('copy.vbo: same content as a-early.vbo'),
      ),
      findsOneWidget,
    );
    expect(
      find.descendant(
        of: notes,
        matching: find.textContaining('notes.txt: not a VBO or RCZ recording'),
      ),
      findsOneWidget,
    );
    Navigator.of(tester.element(find.byType(DayResultsPage))).pop();
    await tester.pumpAndSettle();
    await pumpUntil(
      tester,
      () => find.byKey(const ValueKey('lastDay')).evaluate().isNotEmpty,
    );
    final session1 = tester.getTopLeft(find.text('Session 1'));
    final session2 = tester.getTopLeft(find.text('Session 2'));
    expect(session1.dy, lessThan(session2.dy));
    // Session 1 is the 09:00 recording, whatever the selection order.
    final outcome = runDayImport(job.request);
    expect(outcome.runs.first.run.sourcePath, endsWith('a-early.vbo'));
    expect(outcome.runs.last.run.sourcePath, endsWith('b-late.vbo'));
    expect(
      find.text('No laps: the recording has no start/finish line.'),
      findsNWidgets(2),
    );
    expect(find.text('Cancel'), findsNothing);
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('the import page speaks Polish', (tester) async {
    final laps = write('laps.vbo', _lapsVbo);
    final copy = write('copy.vbo', _lapsVbo);
    final other = write('notes.txt', 'not a recording');
    pickers.recordings = [laps, copy, other];
    await tester.binding.setSurfaceSize(const Size(800, 2000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await show(tester, locale: const Locale('pl'));
    expect(find.text('Start'), findsOneWidget);
    expect(find.text('Import sessions…'), findsNothing);
    expect(find.text('Importuj sesje…'), findsOneWidget);

    await pick(tester, button: 'Importuj sesje…');
    expect(find.text('Wyszukiwanie zapisów telemetrii…'), findsOneWidget);
    importer.jobs.single.finish();
    await tester.pumpAndSettle();
    expect(find.textContaining('Uwagi do importu'), findsOneWidget);
    expect(
      find.textContaining('copy.vbo: ta sama zawartość co laps.vbo'),
      findsOneWidget,
    );
    Navigator.of(tester.element(find.byType(DayResultsPage))).pop();
    await tester.pumpAndSettle();
    await pumpUntil(
      tester,
      () => find.byKey(const ValueKey('lastDay')).evaluate().isNotEmpty,
    );
    expect(find.text('Otwórz dzień'), findsOneWidget);
    expect(find.textContaining('Jeszcze niezapisany'), findsOneWidget);
    expect(find.text('Sesja 1'), findsOneWidget);
    expect(find.text('3 okrążenia'), findsOneWidget);
    expect(find.text('Najlepsze'), findsOneWidget);
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('a session shows its laps and best lap', (tester) async {
    pickers.recordings = [write('laps.vbo', _lapsVbo)];
    await tester.binding.setSurfaceSize(const Size(800, 2000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await show(tester);
    await pick(tester);
    await finishAndGoBack(tester);
    final row = find.byKey(const ValueKey('importSession Session 1'));
    Finder inRow(String text) =>
        find.descendant(of: row, matching: find.text(text));
    expect(inRow('Session 1'), findsOneWidget);
    expect(inRow('3 laps'), findsOneWidget);
    expect(inRow('Best'), findsOneWidget);
    expect(inRow('4.000\u00a0s'), findsOneWidget);
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('only the session of the best lap of the day is purple, and '
      'a session without laps shows no best', (tester) async {
    pickers.recordings = [
      write('a.vbo', circuitVbo([30, 28, 31])),
      write('b.vbo', circuitVbo([29, 32])),
      write('nogate.vbo', _datedVbo(hour: 9)),
    ];
    await tester.binding.setSurfaceSize(const Size(800, 2000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await show(tester);
    await pick(tester);
    final finished = runDayImport(importer.jobs.single.request);
    await finishAndGoBack(tester);
    final ranking = finished.analysis!.ranking!;
    final sessions = find.byKey(const ValueKey('importSessions'));
    final purple = tester
        .widgetList<Text>(
          find.descendant(of: sessions, matching: find.byType(Text)),
        )
        .where((text) => text.style?.color == FetColors.dark.dayBest)
        .toList();
    expect(purple, hasLength(1));
    expect(purple.single.data, displayTime(ranking.bestOfDay!.durationSeconds));
    expect(purple.single.style?.fontWeight, FontWeight.w700);
    // Each ranked session shows its best ranked lap; the recording without
    // a start/finish line shows why, and no best.
    for (final run in ranking.runs) {
      final name = finished.runs.firstWhere((n) => n.run.id == run.runId).name;
      expect(
        find.descendant(
          of: find.byKey(ValueKey('importSession $name')),
          matching: find.text(displayTime(run.bestLap!.durationSeconds)),
        ),
        findsOneWidget,
      );
    }
    expect(
      find.descendant(of: sessions, matching: find.text('Best')),
      findsNWidgets(ranking.runs.length),
    );
    expect(finished.runs, hasLength(ranking.runs.length + 1));
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('a folder is imported with or without subfolders', (
    tester,
  ) async {
    await tester.binding.setSurfaceSize(const Size(800, 1200));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    Directory('${directory.path}/day/sub').createSync(recursive: true);
    write('day/sub/run.vbo', _datedVbo(hour: 9));
    pickers.folder = '${directory.path}/day';
    await show(tester);

    await pick(tester, button: 'Choose a folder…');
    importer.jobs.last.finish();
    await tester.pump();
    expect(
      find.textContaining('No VBO or RCZ recordings were found'),
      findsOneWidget,
    );

    // The label toggles the box too.
    await tester.tap(find.text('Include subfolders'));
    await tester.pump();
    expect(tester.widget<Checkbox>(find.byType(Checkbox).first).value, isTrue);
    await pick(tester, button: 'Choose a folder…');
    expect(importer.jobs.last.request.includeSubfolders, isTrue);
    // A folder is a whole day, which opens by itself.
    await finishAndGoBack(tester);
    expect(find.text('Session 1'), findsOneWidget);
    await tester.pumpWidget(const SizedBox());
    await settleRecovery(tester);
  });

  testWidgets('cancel keeps nothing, even if the result arrives later', (
    tester,
  ) async {
    pickers.recordings = [write('run.vbo', _datedVbo(hour: 9))];
    await show(tester);
    await pick(tester);
    final job = importer.jobs.single;

    await tester.tap(find.text('Cancel'));
    await tester.pump();
    expect(job.cancelled, isTrue);
    expect(
      find.descendant(
        of: find.byKey(const ValueKey('importCancelled')),
        matching: find.text('Import cancelled. Nothing was imported.'),
      ),
      findsOneWidget,
    );
    // A late progress message from the stopped job changes nothing.
    job.progress(1, 1);
    await tester.pump();
    expect(
      find.text('Import cancelled. Nothing was imported.'),
      findsOneWidget,
    );
    expect(find.textContaining('Session 1'), findsNothing);
    expect(find.byKey(const ValueKey('lastDay')), findsNothing);
  });

  testWidgets('a second import is refused while one runs', (tester) async {
    pickers.recordings = [write('run.vbo', _datedVbo(hour: 9))];
    await show(tester);
    await pick(tester);
    expect(
      controller.start(pickers.recordings, includeSubfolders: false),
      isFalse,
    );
    final button = tester.widget<FilledButton>(find.byType(FilledButton));
    expect(button.onPressed, isNull);
    expect(importer.jobs, hasLength(1));
  });

  testWidgets('a failed batch says why and lists each file', (tester) async {
    pickers.recordings = [write('broken.vbo', 'not telemetry')];
    await show(tester);
    await pick(tester);
    importer.jobs.single.finish();
    await tester.pump();
    // In a banner with what to do next.
    expect(
      find.descendant(
        of: find.byKey(const ValueKey('importFailed')),
        matching: find.text('No recording could be imported.'),
      ),
      findsOneWidget,
    );
    expect(
      find.text('Choose the recordings again, or other ones, above.'),
      findsOneWidget,
    );
    expect(find.textContaining('broken.vbo: '), findsOneWidget);
  });

  testWidgets('a recording that cannot be read says why in Polish', (
    tester,
  ) async {
    await tester.binding.setSurfaceSize(const Size(800, 1200));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    pickers.recordings = [write('broken.vbo', 'not telemetry')];
    await show(tester, locale: const Locale('pl'));
    await pick(tester, button: 'Importuj sesje…');
    importer.jobs.single.finish();
    await tester.pump();
    expect(
      find.text('Nie udało się zaimportować żadnego zapisu.'),
      findsOneWidget,
    );
    // telemetry_core's English detail of a damaged file is kept after the
    // Polish sentence.
    expect(
      find.text(
        'broken.vbo: Nie można odczytać pliku VBO: VBO has no [column names] '
        'section.',
      ),
      findsOneWidget,
    );
  });

  testWidgets('on a large screen the page stays 840 wide, centred', (
    tester,
  ) async {
    await tester.binding.setSurfaceSize(const Size(1920, 1080));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await show(tester);
    final card = tester.getRect(find.byKey(const ValueKey('importChoices')));
    expect(card.width, 840);
    // Centred in what the side rail leaves.
    final rail = tester.getRect(find.byKey(const ValueKey('appPlaces'))).width;
    expect(card.center.dx, closeTo((1920 + rail + 1) / 2, 1));
  });

  testWidgets('the import progress is labelled for a screen reader', (
    tester,
  ) async {
    pickers.recordings = [write('run.vbo', _datedVbo(hour: 9))];
    await show(tester);
    await pick(tester);
    expect(
      tester
          .widget<LinearProgressIndicator>(find.byType(LinearProgressIndicator))
          .semanticsLabel,
      'Importing recordings',
    );
  });

  test('times read like the rest of the app', () {
    expect(displayTime(28.662), '28.662\u00a0s');
    expect(displayTime(109.898), '1:49.898');
    expect(displayTime(59.9996), '1:00.000');
    expect(displayTime(double.nan), '—');
  });
}

/// Answers with fixed saved days, newest first.
final class _SavedDays implements DocumentPickers {
  _SavedDays(this.days, {this.saveTo, this.open});

  final List<String> days;

  /// Where Save puts a day; null as if the dialog was closed.
  final String? saveTo;

  /// The day "Open a saved day…" picks; null as if the dialog was closed.
  final String? open;

  @override
  Future<String?> saveLocation(String name) async => saveTo;

  @override
  Future<String?> pickDocument() async => open;

  @override
  Future<String?> pickFolder() async => null;

  @override
  Future<List<String>> savedDays() async => days;
}
