import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:telemetry/day/day_results_controller.dart';
import 'package:telemetry/day/document_pickers.dart';
import 'package:telemetry/import/day_import_controller.dart';
import 'package:telemetry/import/day_import_page.dart';
import 'package:telemetry/import/import_runner.dart';
import 'package:telemetry/import/incoming_recordings.dart';
import 'package:telemetry/main.dart';
import 'package:telemetry_core/telemetry_core.dart';

import '../day/recovery_test.dart' show FileRecoveryStore;

/// A job the test finishes by hand.
final class _FakeJob implements DayImportJob {
  _FakeJob(this.request, this.progress);
  final DayImportRequest request;
  final void Function(int, int) progress;
  final completer = Completer<DayImportOutcome>();
  bool cancelled = false;

  @override
  Future<DayImportOutcome> get result => completer.future;

  @override
  void cancel() {
    cancelled = true;
    if (!completer.isCompleted) {
      completer.completeError(const OperationCancelled());
    }
  }

  /// Runs the real scan and plan synchronously and delivers the result.
  void finish() => completer.complete(runDayImport(request));
}

final class _FakeImporter implements DayImporter {
  final jobs = <_FakeJob>[];

  @override
  DayImportJob start(
    DayImportRequest request,
    void Function(int, int) progress,
  ) {
    final job = _FakeJob(request, progress);
    jobs.add(job);
    return job;
  }
}

/// Prepares additions to a day on the test's own thread.
final class _SyncAppender implements DayAppender {
  @override
  DayAppendJob start(DayAppendRequest request, void Function(int, int) _) =>
      _SyncAppendJob(runDayAppend(request));
}

final class _SyncAppendJob implements DayAppendJob {
  _SyncAppendJob(DayAppendOutcome outcome) : result = Future.value(outcome);

  @override
  final Future<DayAppendOutcome> result;

  @override
  void cancel() {}
}

final class _FakeIncoming implements IncomingRecordings {
  final controller = StreamController<List<String>>.broadcast();

  @override
  Stream<List<String>> get received => controller.stream;
}

final class _FakePickers implements RecordingPickers {
  List<String> recordings = const [];
  String? folder;

  @override
  Future<List<String>> pickRecordings() async => recordings;

  @override
  Future<String?> pickFolder() async => folder;
}

/// A dated RaceChrono export without a start/finish line, starting at
/// [hour]:00 UTC on 2 October 2026.
String _datedVbo({required int hour, int speed = 72, int day = 2}) {
  final clock = hour.toString().padLeft(2, '0');
  final date = day.toString().padLeft(2, '0');
  final rows = StringBuffer();
  for (var i = 0; i < 5; ++i) {
    rows.write('${clock}000$i.000 3000.000000 -1200.000000 $speed\n');
  }
  return 'File created on $date/10/2026 at $clock:00:00\n'
      '[comments]\nGenerated by RaceChrono Pro v10.2.4\n'
      '[column names]\ntime latitude longitude velocity\n[data]\n$rows';
}

/// An undated recording with three laps through its start/finish line.
const String _lapsVbo =
    '[header]\ncoordinate units = degrees\n'
    '[laptiming]\nStart 21.0000 52.0000 21.0000 52.0002 start\n'
    '[column names]\ntime latitude longitude\n[data]\n'
    '0 52.0001 21.0002\n1 52.0001 21.0002\n2 52.0001 20.9998\n'
    '3 52.0008 20.9998\n4 52.0008 21.0002\n5 52.0001 21.0002\n'
    '6 52.0001 20.9998\n7 52.0008 20.9998\n8 52.0008 21.0002\n'
    '10 52.0001 21.0002\n11 52.0001 20.9998\n12 52.0008 20.9998\n'
    '13 52.0008 21.0002\n14 52.0001 21.0002\n15 52.0001 20.9998\n';

void main() {
  late Directory directory;
  late _FakeImporter importer;
  late _FakePickers pickers;
  late DayImportController controller;

  setUp(() {
    directory = Directory.systemTemp.createTempSync('day_import_page');
    importer = _FakeImporter();
    pickers = _FakePickers();
    controller = DayImportController(importer: importer);
  });
  tearDown(() {
    controller.dispose();
    directory.deleteSync(recursive: true);
  });

  String write(String name, String text) {
    final path = '${directory.path}/$name';
    File(path).writeAsStringSync(text, flush: true);
    return path;
  }

  /// Desktop choices by default; [picksFolders] null follows the platform.
  Future<void> show(WidgetTester tester, {bool? picksFolders = true}) =>
      tester.pumpWidget(
        TelemetryApp(
          home: DayImportPage(
            controller: controller,
            pickers: pickers,
            picksFolders: picksFolders,
          ),
        ),
      );

  testWidgets(
    'phones and tablets offer recordings only, not a folder',
    (tester) async {
      final vbo = write('a.vbo', _datedVbo(hour: 9));
      pickers.recordings = [vbo];
      await show(tester, picksFolders: null);

      expect(
        find.text('Choose the day\'s VBO and RCZ recordings.'),
        findsOneWidget,
      );
      expect(find.text('Choose a folder…'), findsNothing);
      expect(find.text('Include subfolders'), findsNothing);

      await tester.tap(find.text('Choose recordings…'));
      await tester.pump();
      expect(controller.isWorking, isTrue);
      importer.jobs.single.finish();
      await tester.pumpAndSettle();
      expect(find.text('1 session imported'), findsOneWidget);
    },
    variant: const TargetPlatformVariant({
      TargetPlatform.iOS,
      TargetPlatform.android,
    }),
  );

  testWidgets(
    'desktops offer a folder too',
    (tester) async {
      await show(tester, picksFolders: null);
      expect(find.text('Choose a folder…'), findsOneWidget);
    },
    variant: const TargetPlatformVariant({
      TargetPlatform.macOS,
      TargetPlatform.windows,
    }),
  );

  testWidgets('recordings shared from another app are imported', (
    tester,
  ) async {
    final incoming = _FakeIncoming();
    final vbo = write('shared.vbo', _datedVbo(hour: 9));
    await tester.pumpWidget(
      TelemetryApp(
        home: DayImportPage(
          controller: controller,
          pickers: pickers,
          incoming: incoming,
        ),
      ),
    );

    incoming.controller.add([vbo]);
    await tester.pump();
    await tester.pump();
    expect(importer.jobs.single.request.paths, [vbo]);
    importer.jobs.single.finish();
    await tester.pumpAndSettle();
    // With no day of today to continue, the shared recording's day opens
    // by itself.
    expect(find.text('Day results'), findsOneWidget);
    Navigator.of(tester.element(find.text('Day results'))).pop();
    await tester.pumpAndSettle();
    expect(find.text('1 session imported'), findsOneWidget);

    // Leaving the page stops listening.
    await tester.pumpWidget(const SizedBox());
    expect(incoming.controller.hasListener, isFalse);
  });

  testWidgets('a share while a day is open imports behind it and says so', (
    tester,
  ) async {
    final incoming = _FakeIncoming();
    final vbo = write('shared.vbo', _datedVbo(hour: 9));
    await tester.pumpWidget(
      TelemetryApp(
        home: DayImportPage(
          controller: controller,
          pickers: pickers,
          incoming: incoming,
        ),
      ),
    );
    final navigator = tester.state<NavigatorState>(find.byType(Navigator));
    navigator.push(
      MaterialPageRoute<void>(
        builder: (_) => const Scaffold(body: Text('An open day')),
      ),
    );
    await tester.pumpAndSettle();

    incoming.controller.add([vbo]);
    await tester.pump();
    await tester.pump(const Duration(milliseconds: 500));
    expect(importer.jobs.single.request.paths, [vbo]);
    expect(find.text('An open day'), findsOneWidget);
    expect(
      find.text(
        'Importing the shared recordings. Go back to Import a day to see them.',
      ),
      findsOneWidget,
    );
  });

  testWidgets('a share while a day is shown adds it to that day', (
    tester,
  ) async {
    final incoming = _FakeIncoming();
    pickers.recordings = [write('a.vbo', _datedVbo(hour: 9))];
    final shared = write('shared.vbo', _datedVbo(hour: 11, speed: 80));
    await tester.binding.setSurfaceSize(const Size(400, 3000));
    addTearDown(() => tester.binding.setSurfaceSize(null));
    await tester.pumpWidget(
      TelemetryApp(
        home: DayImportPage(
          controller: controller,
          pickers: pickers,
          incoming: incoming,
          appender: _SyncAppender(),
        ),
      ),
    );
    await tester.tap(find.text('Choose recordings…'));
    await tester.pump();
    importer.jobs.single.finish();
    await tester.pumpAndSettle();
    await tester.tap(find.text('Show the day\'s results'));
    await tester.pumpAndSettle();

    await tester.runAsync(() async {
      incoming.controller.add([shared]);
      await Future<void>.delayed(const Duration(milliseconds: 50));
    });
    await tester.pumpAndSettle();
    // No second import: the day itself took the recording.
    expect(importer.jobs, hasLength(1));
    expect(find.text('Session 2 added to the day.'), findsOneWidget);
    expect(find.text('Day results'), findsOneWidget);
  });

  group('a share with no day shown', () {
    late FileRecoveryStore store;
    setUp(
      () => store = FileRecoveryStore('${directory.path}/day-recovery.json'),
    );

    /// Keeps an unsaved day of [path] for recovery, as the app does while
    /// a day is open.
    Future<void> keepUnsaved(String path) async {
      final outcome = runDayImport((paths: [path], includeSubfolders: false));
      final day = DayResultsController(
        runs: outcome.runs,
        analysis: outcome.analysis!,
        recovery: store,
      );
      await day.flushRecovery();
      day.dispose();
    }

    /// Lets background isolates run while the page's own work, which runs
    /// in the test's clock, moves on, until [done].
    Future<void> pumpUntil(WidgetTester tester, bool Function() done) async {
      for (var i = 0; i < 200 && !done(); ++i) {
        await tester.runAsync(
          () => Future<void>.delayed(const Duration(milliseconds: 20)),
        );
        await tester.pump();
      }
      expect(done(), isTrue);
    }

    Future<void> showWith(WidgetTester tester, _FakeIncoming incoming) async {
      await tester.binding.setSurfaceSize(const Size(400, 3000));
      addTearDown(() => tester.binding.setSurfaceSize(null));
      await tester.pumpWidget(
        TelemetryApp(
          home: DayImportPage(
            controller: controller,
            pickers: pickers,
            incoming: incoming,
            recovery: store,
            appender: _SyncAppender(),
          ),
        ),
      );
    }

    testWidgets('continues today\'s unsaved day', (tester) async {
      final incoming = _FakeIncoming();
      await tester.runAsync(
        () => keepUnsaved(write('a.vbo', _datedVbo(hour: 10))),
      );
      await showWith(tester, incoming);
      final shared = write('b.vbo', _datedVbo(hour: 12, speed: 80));
      incoming.controller.add([shared]);
      await pumpUntil(
        tester,
        () => find.text('Day results').evaluate().isNotEmpty,
      );
      await tester.pumpAndSettle();
      expect(importer.jobs, isEmpty);
      expect(find.text('Day results'), findsOneWidget);
      expect(find.text('Session 2 added to the day.'), findsOneWidget);

      // Closing the day writes its recovery file; let that finish here, not
      // in the next test.
      await tester.pumpWidget(const SizedBox());
      for (var i = 0; i < 20; ++i) {
        await tester.runAsync(
          () => Future<void>.delayed(const Duration(milliseconds: 20)),
        );
        await tester.pump();
      }
    });

    testWidgets('a share while a day is being restored goes to that day', (
      tester,
    ) async {
      final incoming = _FakeIncoming();
      await tester.runAsync(
        () => keepUnsaved(write('a.vbo', _datedVbo(hour: 10))),
      );
      await showWith(tester, incoming);
      await pumpUntil(tester, () => find.text('Restore').evaluate().isNotEmpty);
      await tester.tap(find.text('Restore'));
      // Shared before the restored day could open.
      incoming.controller.add([write('b.vbo', _datedVbo(hour: 12, speed: 80))]);
      await pumpUntil(
        tester,
        () => find.text('Session 2 added to the day.').evaluate().isNotEmpty,
      );
      expect(importer.jobs, isEmpty);
      expect(find.text('Day results'), findsOneWidget);

      await tester.pumpWidget(const SizedBox());
      for (var i = 0; i < 20; ++i) {
        await tester.runAsync(
          () => Future<void>.delayed(const Duration(milliseconds: 20)),
        );
        await tester.pump();
      }
    });

    testWidgets('another day\'s unsaved work is not replaced by today\'s', (
      tester,
    ) async {
      final incoming = _FakeIncoming();
      // Today's day, saved in the app.
      final saved = '${directory.path}/Today.fetproject';
      await tester.runAsync(() async {
        final outcome = runDayImport((
          paths: [write('a.vbo', _datedVbo(hour: 10))],
          includeSubfolders: false,
        ));
        final day = DayResultsController(
          runs: outcome.runs,
          analysis: outcome.analysis!,
        );
        await day.save(saved);
        day.dispose();
        // Then an older day changed and left unsaved.
        await keepUnsaved(write('x.vbo', _datedVbo(hour: 9, day: 5)));
      });
      final before = await tester.runAsync(store.load);
      await tester.binding.setSurfaceSize(const Size(400, 3000));
      addTearDown(() => tester.binding.setSurfaceSize(null));
      await tester.pumpWidget(
        TelemetryApp(
          home: DayImportPage(
            controller: controller,
            pickers: pickers,
            incoming: incoming,
            recovery: store,
            appender: _SyncAppender(),
            documents: _SavedDays([saved]),
          ),
        ),
      );
      final shared = write('b.vbo', _datedVbo(hour: 12, speed: 80));
      incoming.controller.add([shared]);
      await pumpUntil(tester, () => importer.jobs.isNotEmpty);
      // Imported here, next to the offer to restore the other day.
      expect(importer.jobs.single.request.paths, [shared]);
      for (var i = 0; i < 10; ++i) {
        await tester.runAsync(
          () => Future<void>.delayed(const Duration(milliseconds: 20)),
        );
        await tester.pump();
      }
      final after = await tester.runAsync(store.load);
      expect(after!.timestamp, before!.timestamp);
      expect(
        (after.document['event'] as Map)['id'],
        (before.document['event'] as Map)['id'],
      );
      final runs = (readDayDocument(saved)['event'] as Map)['runs'] as List;
      expect(runs, hasLength(1));
    });

    testWidgets('a recording of another date starts its own day', (
      tester,
    ) async {
      final incoming = _FakeIncoming();
      await tester.runAsync(
        () => keepUnsaved(write('a.vbo', _datedVbo(hour: 10))),
      );
      await showWith(tester, incoming);
      final shared = write('b.vbo', _datedVbo(hour: 12, day: 5));
      incoming.controller.add([shared]);
      await pumpUntil(tester, () => importer.jobs.isNotEmpty);
      expect(importer.jobs.single.request.paths, [shared]);
    });
  });

  test('iOS picks by type identifier, desktops by extension', () {
    // file_selector on iOS refuses a group without type identifiers.
    final ios = recordingTypeGroup(TargetPlatform.iOS);
    expect(ios.uniformTypeIdentifiers, isNotEmpty);
    for (final platform in [TargetPlatform.macOS, TargetPlatform.windows]) {
      final group = recordingTypeGroup(platform);
      expect(group.extensions, containsAll(['vbo', 'rcz']));
      expect(group.uniformTypeIdentifiers, isNull);
    }
  });

  test('Android picks with the host picker, keeping file names', () async {
    // file_selector would hand back "session.bin" for a picked "session.vbo".
    debugDefaultTargetPlatformOverride = TargetPlatform.android;
    addTearDown(() => debugDefaultTargetPlatformOverride = null);
    final messenger =
        TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger;
    final calls = <String>[];
    Object? picked = ['/data/picked/1/session.vbo', '/data/picked/2/day.rcz'];
    messenger.setMockMethodCallHandler(androidPickerChannel, (call) async {
      calls.add(call.method);
      return picked;
    });
    addTearDown(
      () => messenger.setMockMethodCallHandler(androidPickerChannel, null),
    );

    const pickers = PlatformRecordingPickers();
    expect(await pickers.pickRecordings(), [
      '/data/picked/1/session.vbo',
      '/data/picked/2/day.rcz',
    ]);
    picked = null;
    expect(await pickers.pickRecordings(), isEmpty);
    expect(calls, ['pick', 'pick']);
  });

  testWidgets('imports picked recordings as sessions in recording order', (
    tester,
  ) async {
    final late = write('b-late.vbo', _datedVbo(hour: 11));
    final early = write('a-early.vbo', _datedVbo(hour: 9, speed: 80));
    final copy = write('copy.vbo', _datedVbo(hour: 9, speed: 80));
    final other = write('notes.txt', 'not a recording');
    pickers.recordings = [late, early, copy, other];
    await show(tester);

    await tester.tap(find.text('Choose recordings…'));
    await tester.pump();
    expect(find.text('Looking for recordings…'), findsOneWidget);
    expect(find.text('Cancel'), findsOneWidget);
    final job = importer.jobs.single;
    expect(job.request.includeSubfolders, isFalse);

    job.progress(1, 3);
    await tester.pump();
    expect(find.text('Preparing recording 2 of 3…'), findsOneWidget);

    job.finish();
    await tester.pump();
    expect(find.text('2 sessions imported'), findsOneWidget);
    final session1 = tester.getTopLeft(find.text('Session 1'));
    final session2 = tester.getTopLeft(find.text('Session 2'));
    expect(session1.dy, lessThan(session2.dy));
    // Session 1 is the 09:00 recording, whatever the selection order.
    final finished = controller.state as DayImportFinished;
    expect(finished.runs.first.run.sourcePath, endsWith('a-early.vbo'));
    expect(finished.runs.last.run.sourcePath, endsWith('b-late.vbo'));
    expect(
      find.text('No laps: the recording has no start/finish line.'),
      findsNWidgets(2),
    );
    expect(
      find.textContaining('copy.vbo: same content as a-early.vbo'),
      findsOneWidget,
    );
    expect(
      find.textContaining('notes.txt: not a VBO or RCZ recording'),
      findsOneWidget,
    );
    expect(find.text('Cancel'), findsNothing);
  });

  testWidgets('a session shows its laps and best lap', (tester) async {
    pickers.recordings = [write('laps.vbo', _lapsVbo)];
    await show(tester);
    await tester.tap(find.text('Choose recordings…'));
    await tester.pump();
    importer.jobs.single.finish();
    await tester.pump();
    expect(find.text('Session 1'), findsOneWidget);
    expect(find.text('3 laps · best 4.000 s'), findsOneWidget);
  });

  testWidgets('a folder is imported with or without subfolders', (
    tester,
  ) async {
    Directory('${directory.path}/day/sub').createSync(recursive: true);
    write('day/sub/run.vbo', _datedVbo(hour: 9));
    pickers.folder = '${directory.path}/day';
    await show(tester);

    await tester.tap(find.text('Choose a folder…'));
    await tester.pump();
    importer.jobs.last.finish();
    await tester.pump();
    expect(
      find.textContaining('No VBO or RCZ recordings were found'),
      findsOneWidget,
    );

    await tester.tap(find.byType(Checkbox));
    await tester.tap(find.text('Choose a folder…'));
    await tester.pump();
    expect(importer.jobs.last.request.includeSubfolders, isTrue);
    importer.jobs.last.finish();
    await tester.pump();
    expect(find.text('1 session imported'), findsOneWidget);
    expect(find.text('Session 1'), findsOneWidget);
  });

  testWidgets('cancel keeps nothing, even if the result arrives later', (
    tester,
  ) async {
    pickers.recordings = [write('run.vbo', _datedVbo(hour: 9))];
    await show(tester);
    await tester.tap(find.text('Choose recordings…'));
    await tester.pump();
    final job = importer.jobs.single;

    await tester.tap(find.text('Cancel'));
    await tester.pump();
    expect(job.cancelled, isTrue);
    expect(
      find.text('Import cancelled. Nothing was imported.'),
      findsOneWidget,
    );
    // A late progress message from the stopped job changes nothing.
    job.progress(1, 1);
    await tester.pump();
    expect(
      find.text('Import cancelled. Nothing was imported.'),
      findsOneWidget,
    );
    expect(find.textContaining('Session'), findsNothing);
  });

  testWidgets('a second import is refused while one runs', (tester) async {
    pickers.recordings = [write('run.vbo', _datedVbo(hour: 9))];
    await show(tester);
    await tester.tap(find.text('Choose recordings…'));
    await tester.pump();
    expect(
      controller.start(pickers.recordings, includeSubfolders: false),
      isFalse,
    );
    final button = tester.widget<FilledButton>(find.byType(FilledButton));
    expect(button.onPressed, isNull);
    expect(importer.jobs, hasLength(1));
  });

  testWidgets('a failed batch says why and lists each file', (tester) async {
    pickers.recordings = [write('broken.vbo', 'not telemetry')];
    await show(tester);
    await tester.tap(find.text('Choose recordings…'));
    await tester.pump();
    importer.jobs.single.finish();
    await tester.pump();
    expect(find.text('No recording could be imported.'), findsOneWidget);
    expect(find.textContaining('broken.vbo: '), findsOneWidget);
  });

  test('times read like the rest of the app', () {
    expect(displayTime(28.662), '28.662 s');
    expect(displayTime(109.898), '1:49.898');
    expect(displayTime(59.9996), '1:00.000');
    expect(displayTime(double.nan), '—');
  });
}

/// Answers with fixed saved days, newest first.
final class _SavedDays implements DocumentPickers {
  _SavedDays(this.days);

  final List<String> days;

  @override
  Future<String?> saveLocation(String name) async => null;

  @override
  Future<String?> pickDocument() async => null;

  @override
  Future<String?> pickFolder() async => null;

  @override
  Future<List<String>> savedDays() async => days;
}
