// One synthetic drive recorded twice, as a RaceChrono VBO and as an RCZ
// archive, for source fusion (FET-51). No real data: a 100 m circle with a
// start line, laps at the given speeds and a slow, non-periodic wobble, so
// the speed traces align unambiguously.
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import '../rcz/rcz_fixture.dart';

/// The start of the VBO's first sample: 1 August 2026, 10:00:00 UTC.
final int fusionPairOrigin = DateTime.utc(2026, 8, 1, 10).millisecondsSinceEpoch;

/// Writes `<name>.vbo` and `<name>.rcz` into [directory] and returns their
/// paths. The RCZ starts 0.1 s after the VBO on the same clock and also
/// records engine speed (`rpm-obd`), which the VBO does not. With
/// [satellites], both record a unitless satellite count, the RCZ's
/// [satelliteDifference] higher, so the two disagree on it.
(String vbo, String rcz) writeFusionPair(
  String directory, {
  String name = 'drive',
  List<double> speeds = const [30, 27, 32, 25, 29, 31, 26, 33, 28, 30],
  bool satellites = false,
  double satelliteDifference = 5,
}) {
  const lat0 = 52.0, lon0 = 21.0;
  const metersPerDegree = 6371000.0 * math.pi / 180.0;
  final cosLat = math.cos(lat0 * math.pi / 180.0);
  (double, double) degrees(double east, double north) =>
      (lat0 + north / metersPerDegree, lon0 + east / (metersPerDegree * cosLat));

  // The drive at 10 Hz: time, latitude, longitude, speed (m/s), rpm, sats.
  final samples = <(double, double, double, double, double, double)>[];
  var travelled = 0.0, t = 0.0;
  final total = (speeds.length + 0.5) * 2 * math.pi;
  while (travelled < total) {
    final lap = math.min(travelled ~/ (2 * math.pi), speeds.length - 1);
    final a = -0.25 + travelled;
    final speed = speeds[lap] * (0.8 + 0.2 * math.cos(2 * a)) + 1.5 * math.sin(0.37 * t);
    final (lat, lon) = degrees(-100 + 100 * math.cos(a), 100 * math.sin(a));
    final rpm = 2000 + speed * 120;
    final sats = 10 + (4 * math.sin(0.05 * t)).roundToDouble();
    samples.add((t, lat, lon, speed, rpm, sats));
    travelled += speed / 10 / 100;
    t += 0.1;
  }

  // The VBO: RaceChrono Pro 10.2.4, arc-minutes, west-positive longitude, a
  // centre-and-direction start gate at the circle's start point.
  String two(int value) => value.toString().padLeft(2, '0');
  final origin = DateTime.fromMillisecondsSinceEpoch(fusionPairOrigin, isUtc: true);
  String minutes(double value) => (value * 60).toStringAsFixed(6);
  final (gateLat, gateLon) = degrees(0, 0);
  final (backLat, backLon) = degrees(0, -20);
  final vbo = StringBuffer(
    'File created on ${two(origin.day)}/${two(origin.month)}/${origin.year} at '
    '${two(origin.hour)}:${two(origin.minute)}:${two(origin.second)}\n'
    '[header]\ntime\nlatitude\nlongitude\nvelocity kmh\n${satellites ? 'sats\n' : ''}'
    '[comments]\nGenerated by RaceChrono Pro v10.2.4\n'
    '[laptiming]\nStart ${minutes(-gateLon)} ${minutes(gateLat)} '
    '${minutes(-backLon)} ${minutes(backLat)} start\n'
    '[column names]\ntime latitude longitude velocity${satellites ? ' sats' : ''}\n[data]\n',
  );
  for (final (time, lat, lon, speed, _, sats) in samples) {
    final clock = origin.add(Duration(milliseconds: (time * 1000).round()));
    vbo.write(
      '${two(clock.hour)}${two(clock.minute)}${two(clock.second)}.'
      '${(clock.millisecond ~/ 10).toString().padLeft(2, '0')} '
      '${minutes(lat)} ${minutes(-lon)} ${(speed * 3.6).toStringAsFixed(2)}'
      '${satellites ? ' ${sats.toStringAsFixed(0)}' : ''}\n',
    );
  }
  final vboPath = '$directory/$name.vbo';
  File(vboPath).writeAsStringSync(vbo.toString());

  // The RCZ: from the second sample on, east-positive degrees.
  final rows = samples.skip(1).toList();
  final first = fusionPairOrigin + 100;
  final times = ByteData(rows.length * 8), position = ByteData(rows.length * 8);
  final speed = ByteData(rows.length * 4), sats = ByteData(rows.length * 4);
  final rpm = ByteData(rows.length * 8);
  for (var i = 0; i < rows.length; ++i) {
    final (time, lat, lon, metres, revolutions, count) = rows[i];
    times.setInt64(i * 8, fusionPairOrigin + (time * 1000).round(), Endian.little);
    position.setInt32(i * 8, (lat * 6000000).round(), Endian.little);
    position.setInt32(i * 8 + 4, (lon * 6000000).round(), Endian.little);
    speed.setInt32(i * 4, (metres * 1000).round(), Endian.little);
    sats.setInt32(i * 4, (count + satelliteDifference).round(), Endian.little);
    rpm.setFloat64(i * 8, revolutions, Endian.little);
  }
  final ticks = times.buffer.asUint8List();
  final rczPath = '$directory/$name.rcz';
  File(rczPath).writeAsBytesSync(
    zip({
      'session.json': text(
        '{"version":1,"firstTimestamp":$first,"trackName":"Synthetic","laps":[]}',
      ),
      'sessionfragment.json': text(
        '{"version":1,"firstTimestamp":$first,"primaryGpsDeviceIndex":300}',
      ),
      'channel_1_300_0_1_1': ticks,
      'channel_1_300_0_3_1': position.buffer.asUint8List(),
      'channel_1_300_0_4_0': speed.buffer.asUint8List(),
      if (satellites) 'channel_1_300_0_30002_0': sats.buffer.asUint8List(),
      'channel_5_200_10024_1_1': ticks,
      'channel2_5_200_10024_10024_3': rpm.buffer.asUint8List(),
    }),
  );
  return (vboPath, rczPath);
}
