// Ports VBOOverlay native/tests/TelemetryImportTests.cpp (synthetic
// recordings only) and the KAN-119 run naming.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:telemetry_core/telemetry_core.dart';
import 'package:test/test.dart';

import '../rcz/rcz_fixture.dart';

String vbo([String speed = '72']) =>
    '[header]\ncoordinate units = degrees\n[column names]\ntime latitude longitude velocity heart_rate\n[data]\n'
    '0 50 20 $speed 120\n1 50.001 20.001 80 125\n';

/// A synthetic 31-second moving recording as VBO. Its time origin is its
/// first sample; the RCZ below keeps a 100 ms delay to its first sample.
String movingVbo({bool stationary = false, bool distant = false, bool sparse = false}) {
  final text = StringBuffer(
    '[header]\ncoordinate units = degrees\n[column names]\ntime latitude longitude velocity\n[data]\n',
  );
  for (var i = 0; i < 32; ++i) {
    if (sparse && i > 7 && i < 24) continue;
    final latitude = (distant ? 51.0 : 50.0) + (stationary ? 0 : i * .0001);
    text.write('$i ${latitude.toStringAsFixed(6)} 20 72\n');
  }
  return text.toString();
}

Uint8List movingRcz({bool stationary = false}) {
  final timestamps = ByteData(32 * 8), coordinates = ByteData(32 * 8), speed = ByteData(32 * 4);
  for (var i = 0; i < 32; ++i) {
    timestamps.setInt64(i * 8, fixtureOrigin + 100 + i * 1000, Endian.little);
    coordinates.setInt32(i * 8, 300000000 + (stationary ? 0 : i * 600), Endian.little);
    coordinates.setInt32(i * 8 + 4, 120000000, Endian.little);
    speed.setInt32(i * 4, 20000, Endian.little);
  }
  final members = fixtureMembers()
    ..['channel_1_300_0_1_1'] = timestamps.buffer.asUint8List()
    ..['channel_1_300_0_3_1'] = coordinates.buffer.asUint8List()
    ..['channel_1_300_0_4_0'] = speed.buffer.asUint8List();
  return zip(members);
}

String two(int value) => value.toString().padLeft(2, '0');

void main() {
  late Directory directory;
  setUp(() => directory = Directory.systemTemp.createTempSync('import_plan'));
  tearDown(() => directory.deleteSync(recursive: true));

  String write(String name, Object bytes) {
    final path = '${directory.path}/$name';
    final file = File(path);
    if (bytes is String) {
      file.writeAsStringSync(bytes, flush: true);
    } else {
      file.writeAsBytesSync(bytes as List<int>, flush: true);
    }
    return path;
  }

  test('matches dated exports with different coordinate conventions', () {
    final origin = DateTime.fromMillisecondsSinceEpoch(fixtureOrigin + 100, isUtc: true);
    String recording({required bool wrongSign}) {
      final text = StringBuffer(
        'File created on ${two(origin.day)}/${two(origin.month)}/${origin.year} at '
        '${two(origin.hour)}:${two(origin.minute)}:${two(origin.second)}\n'
        '[comments]\nGenerated by RaceChrono Pro v10.2.4\n'
        '[column names]\ntime latitude longitude velocity\n[data]\n',
      );
      for (var i = 0; i < 32; ++i) {
        final t = origin.add(Duration(seconds: i));
        final clock =
            '${two(t.hour)}${two(t.minute)}${two(t.second)}.${t.millisecond.toString().padLeft(3, '0')}';
        final latitude = ((50.0 + i * .0001) * 60.0).toStringAsFixed(9);
        text.write('$clock $latitude ${wrongSign ? '1200' : '-1200'} 72\n');
      }
      return text.toString();
    }

    final vboPath = write('export.vbo', recording(wrongSign: false));
    final rczPath = write('archive.rcz', movingRcz());
    final plan = prepareTelemetryImport([rczPath, vboPath]);
    expect(plan.runs, hasLength(2));
    expect(plan.possibleSameRuns, hasLength(1));
    expect(automaticVboPrimaries(plan)[plan.runs[0].id], plan.runs[1].id);
    final wrong = write('wrong.vbo', recording(wrongSign: true));
    expect(prepareTelemetryImport([wrong, rczPath]).possibleSameRuns, isEmpty);
    // The same pairing when each recording was prepared on its own, as when
    // one is added to a day that has the other.
    final vboRun = prepareTelemetryImport([vboPath]).runs.single;
    final rczRun = prepareTelemetryImport([rczPath]).runs.single;
    expect(sameDriveInOtherFormat(rczRun, vboRun), isTrue);
    expect(sameDriveInOtherFormat(vboRun, rczRun), isTrue);
    expect(sameDriveInOtherFormat(vboRun, vboRun), isFalse);
    expect(sameDriveInOtherFormat(prepareTelemetryImport([wrong]).runs.single, rczRun), isFalse);
  });

  test('reports completed file progress', () {
    final good = write('good.vbo', vbo());
    final bad = write('bad.rcz', 'invalid');
    final counts = <int>[];
    final plan = prepareTelemetryImport(
      [good, good, bad],
      progress: (processed, total) {
        if (total == 3) counts.add(processed);
      },
    );
    expect(counts, [0, 1, 2, 3]);
    expect(plan.files, hasLength(3));
  });

  test('imports independent runs without combining clocks', () {
    final a = write('first.VBO', vbo());
    final b = write('second.rcz', zip(fixtureMembers()));
    final plan = prepareTelemetryImport([a, b]);
    expect(plan.runs, hasLength(2));
    expect(plan.files.map((f) => f.status), everyElement(TelemetryImportFileStatus.ready));
    final first = plan.runs[0], second = plan.runs[1];
    expect(first.id, isNot(second.id));
    expect(first.telemetry.duration, 1.0);
    expect(second.telemetry.duration, 2.0);
    expect(first.telemetry.valueAt('heartRate', 0), 120.0);
    expect(second.telemetry.valueAt('heartRate', .15), 120.0);
    expect(first.telemetry.valueAt('brake', 0), isNull);
    expect(second.telemetry.valueAt('speed', 1), isNull);
    expect(first.laps.status, LapSessionStatus.noSourceStartGate);
    final direct = deriveSourceLapSession(second.telemetry);
    expect(second.laps.status, direct.status);
    expect(second.laps.timedLaps.length, direct.timedLaps.length);
    expect(first.format, RecordingFormat.vbo);
    expect(second.format, RecordingFormat.rcz);
    expect(first.contentSha256, matches(RegExp(r'^[0-9a-f]{64}$')));
    expect(first.sourceId, startsWith('sha256:'));
    expect(plan.possibleSameRuns, isEmpty);
  });

  test('deduplicates bytes, not file names, and keeps every result', () {
    final a = write('session.vbo', vbo());
    final copy = write('renamed.VBO', vbo());
    final other = write('different.vbo', vbo('73'));
    final plan = prepareTelemetryImport([a, copy, other, a]);
    expect(plan.runs, hasLength(2));
    expect(plan.files, hasLength(4));
    expect(plan.files[1].status, TelemetryImportFileStatus.duplicate);
    expect(plan.files[3].status, TelemetryImportFileStatus.duplicate);
    expect(plan.files[1].requestedPath, copy);
    expect(plan.files[0].runId, plan.files[1].runId);
    expect(plan.files[0].runId, isNot(plan.files[2].runId));
    final reordered = prepareTelemetryImport([other, copy]);
    expect(reordered.runs[0].id, plan.runs[1].id);
    expect(reordered.runs[1].id, plan.runs[0].id);
  });

  test('keeps complete laps within their own run', () {
    final a = write(
      'laps.vbo',
      '[header]\ncoordinate units = degrees\n[laptiming]\nStart 21.0000 52.0000 21.0000 52.0002 start\n'
          '[column names]\ntime latitude longitude\n[data]\n'
          '0 52.0001 21.0002\n1 52.0001 21.0002\n2 52.0001 20.9998\n'
          '3 52.0008 20.9998\n4 52.0008 21.0002\n5 52.0001 21.0002\n'
          '6 52.0001 20.9998\n7 52.0008 20.9998\n8 52.0008 21.0002\n'
          '10 52.0001 21.0002\n11 52.0001 20.9998\n12 52.0008 20.9998\n'
          '13 52.0008 21.0002\n14 52.0001 21.0002\n15 52.0001 20.9998\n',
    );
    final b = write('other.vbo', vbo());
    final plan = prepareTelemetryImport([a, b]);
    expect(plan.runs, hasLength(2));
    final laps = plan.runs[0].laps;
    expect(laps.status, LapSessionStatus.available);
    expect(laps.timedLaps, hasLength(3));
    expect(laps.lapTraces, hasLength(3));
    expect(laps.timedLaps[0].durationSeconds, closeTo(4.0, .001));
    expect(laps.timedLaps[1].durationSeconds, closeTo(5.0, .001));
    expect(laps.timedLaps[2].durationSeconds, closeTo(4.0, .001));
    expect(laps.fastestLapIndex, 0);
    expect(plan.runs[1].laps.timedLaps, isEmpty);
  });

  test('keeps the selected format for a linked source', () {
    final backing = write('recording.data', vbo());
    final selected = '${directory.path}/selected.vbo';
    Link(selected).createSync(backing);
    final plan = prepareTelemetryImport([selected]);
    expect(plan.runs, hasLength(1));
    expect(plan.runs[0].format, RecordingFormat.vbo);
    expect(plan.runs[0].sourcePath, File(selected).absolute.path);
  }, testOn: '!windows');

  test('isolates failures and does not deduplicate unparsed content', () {
    final good = write('good.vbo', vbo());
    final bad = write('bad.vbo', 'not telemetry');
    final badCopy = write('bad-copy.vbo', 'not telemetry');
    final wrongFormat = write('wrong.rcz', vbo());
    final empty = write('empty.vbo', '');
    final plan = prepareTelemetryImport([
      bad,
      good,
      badCopy,
      wrongFormat,
      empty,
      '${directory.path}/missing.vbo',
      directory.path,
      'wrong.csv',
    ]);
    expect(plan.runs, hasLength(1));
    expect(plan.files, hasLength(8));
    expect(plan.files[1].status, TelemetryImportFileStatus.ready);
    for (final index in [0, 2, 3, 4, 5, 6, 7]) {
      final file = plan.files[index];
      expect(file.status, TelemetryImportFileStatus.error, reason: '$index');
      expect(file.runId, isEmpty);
      expect(file.message, isNotEmpty);
    }
  });

  test('enforces file and batch budgets', () {
    final a = write('a.vbo', vbo());
    final b = write('b.vbo', vbo('73'));
    final size = utf8.encode(vbo()).length;
    expect(
      () => prepareTelemetryImport([a, b], limits: const TelemetryImportLimits(maximumFiles: 1)),
      throwsA(isA<ResourceLimitError>()),
    );
    expect(
      prepareTelemetryImport([
        a,
      ], limits: TelemetryImportLimits(maximumFileBytes: size - 1)).files[0].status,
      TelemetryImportFileStatus.error,
    );
    final limits = TelemetryImportLimits(maximumBatchBytes: size);
    final plan = prepareTelemetryImport([a, b], limits: limits);
    expect(plan.runs, hasLength(1));
    expect(plan.files[0].status, TelemetryImportFileStatus.ready);
    expect(plan.files[1].status, TelemetryImportFileStatus.error);
    expect(plan.files[1].message, contains('input-byte'));
    // Repeated selections use the input budget too.
    expect(
      prepareTelemetryImport([a, a], limits: limits).files[1].status,
      TelemetryImportFileStatus.error,
    );
  });

  test('bounds admitted channel samples', () {
    final a = write('a.vbo', vbo());
    final b = write('b.vbo', vbo('73'));
    // Four channels, two samples each.
    final plan = prepareTelemetryImport([
      a,
      b,
      a,
    ], limits: const TelemetryImportLimits(maximumRetainedChannelSamples: 8));
    expect(plan.runs, hasLength(1));
    expect(plan.files[0].status, TelemetryImportFileStatus.ready);
    expect(plan.files[1].status, TelemetryImportFileStatus.error);
    expect(plan.files[1].message, contains('decoded-sample'));
    expect(plan.files[2].status, TelemetryImportFileStatus.duplicate);
    expect(
      prepareTelemetryImport([
        a,
      ], limits: const TelemetryImportLimits(maximumRetainedChannelSamples: 7)).runs,
      isEmpty,
    );
  });

  test('rejects invalid limits', () {
    const ceilings = TelemetryImportLimits();
    for (final limits in [
      const TelemetryImportLimits(maximumFiles: 0),
      TelemetryImportLimits(maximumFileBytes: ceilings.maximumFileBytes + 1),
      TelemetryImportLimits(maximumBatchBytes: ceilings.maximumBatchBytes + 1),
      TelemetryImportLimits(
        maximumRetainedChannelSamples: ceilings.maximumRetainedChannelSamples + 1,
      ),
    ]) {
      expect(() => prepareTelemetryImport([], limits: limits), throwsArgumentError);
    }
    expect(prepareTelemetryImport([]).runs, isEmpty);
  });

  test('cancellation never returns a partial plan', () {
    final a = write('a.vbo', vbo());
    expect(
      () => prepareTelemetryImport([a], cancelled: () => true),
      throwsA(isA<OperationCancelled>()),
    );
    var singleChecks = 0;
    prepareTelemetryImport(
      [a],
      cancelled: () {
        ++singleChecks;
        return false;
      },
    );
    final b = write('b.vbo', vbo('73'));
    var checks = 0;
    expect(
      () => prepareTelemetryImport([a, b], cancelled: () => ++checks >= singleChecks),
      throwsA(isA<OperationCancelled>()),
    );
    expect(checks, singleChecks);
  });

  test('reports cross-format candidates without merging', () {
    final v = write('unrelated-name.vbo', movingVbo());
    final r = write('another-name.rcz', movingRcz());
    final plan = prepareTelemetryImport([v, r]);
    expect(plan.runs, hasLength(2));
    expect(plan.possibleSameRuns, hasLength(1));
    final match = plan.possibleSameRuns.single;
    expect(match.firstRunId, plan.runs[0].id);
    expect(match.secondRunId, plan.runs[1].id);
    expect(match.comparedGpsSamples, 32);
    expect(match.maximumSeparationMeters, lessThan(.01));
    expect(match.gpsDurationDifferenceSeconds, lessThan(.001));
    expect(match.reviewReason, contains('Confirm recording date'));
    // Undated VBO: evidence only, no automatic grouping.
    expect(automaticVboPrimaries(plan)[plan.runs[1].id], plan.runs[1].id);
  });

  test('rejects content changed between hashing and parsing', () {
    final a = write('a.vbo', vbo());
    var checks = 0, changed = false;
    final plan = prepareTelemetryImport(
      [a],
      cancelled: () {
        // After the first full hash, before the second one.
        if (!changed && ++checks == 5) {
          write('a.vbo', vbo('73'));
          changed = true;
        }
        return false;
      },
    );
    expect(changed, isTrue);
    expect(plan.runs, isEmpty);
    expect(plan.files[0].status, TelemetryImportFileStatus.error);
    expect(plan.files[0].message, contains('changed during import'));
  });

  group('rejects weak match evidence:', () {
    for (final kind in ['stationary', 'distant', 'sparse', 'same-format', 'duration']) {
      test(kind, () {
        var text = movingVbo(
          stationary: kind == 'stationary',
          distant: kind == 'distant',
          sparse: kind == 'sparse',
        );
        if (kind == 'duration') text = text.replaceFirst('31 50.003100', '40 50.003100');
        final a = write('same-name.vbo', text);
        final b = kind == 'same-format'
            ? write('other.vbo', '${movingVbo()}\n')
            : write('same-name.rcz', movingRcz(stationary: kind == 'stationary'));
        final plan = prepareTelemetryImport([a, b]);
        expect(plan.runs, hasLength(2));
        expect(plan.possibleSameRuns, isEmpty);
      });
    }
  });

  test('keeps ambiguous one-to-many matches for review', () {
    final a = write('a.vbo', movingVbo());
    final b = write('b.vbo', '${movingVbo()}\n');
    final r = write('recording.rcz', movingRcz());
    final plan = prepareTelemetryImport([a, b, r]);
    expect(plan.runs, hasLength(3));
    expect(plan.possibleSameRuns, hasLength(2));
    final groups = automaticVboPrimaries(plan);
    for (final run in plan.runs) {
      expect(groups[run.id], run.id);
    }
  });

  test('names runs "Session N" in recording order, undated last', () {
    final undated = write('undated.vbo', vbo());
    final late = write('late.rcz', zip(fixtureMembers()));
    final early = fixtureMembers()
      ..['session.json'] = text(
        '{"version":1,"firstTimestamp":1779999000000,"trackName":"Synthetic","laps":[]}',
      )
      ..['sessionfragment.json'] = text(
        '{"version":1,"firstTimestamp":1779999000000,"primaryGpsDeviceIndex":300}',
      );
    for (final name in early.keys.where((name) => name.endsWith('_1_1')).toList()) {
      final data = ByteData.sublistView(early[name]!);
      final shifted = ByteData(data.lengthInBytes);
      for (var at = 0; at < data.lengthInBytes; at += 8) {
        shifted.setInt64(at, data.getInt64(at, Endian.little) - 1000000, Endian.little);
      }
      early[name] = shifted.buffer.asUint8List();
    }
    final earlyPath = write('early.rcz', zip(early));
    final plan = prepareTelemetryImport([undated, late, earlyPath]);
    expect(plan.runs, hasLength(3));
    final named = nameRunsInRecordingOrder(plan.runs, existingRuns: 2);
    expect([for (final n in named) n.name], ['Session 3', 'Session 4', 'Session 5']);
    expect(
      [for (final n in named) n.run.sourcePath],
      [File(earlyPath).absolute.path, File(late).absolute.path, File(undated).absolute.path],
    );
  });

  test('a stale generation or changed sources never commit', () {
    final generation = ImportGeneration();
    final first = generation.begin(['sha256:a']);
    expect(generation.isCurrent(first), isTrue);
    final second = generation.begin(['sha256:a', 'sha256:b']);
    expect(generation.isCurrent(first), isFalse);
    expect(generation.isCurrent(second), isTrue);
    generation.invalidate();
    expect(generation.isCurrent(second), isFalse);
  });
}
